nextcloud/polls

appinfo/info.xml
add nextcloud version info - tests with 11 went ok; 10.2 ongoing and
look good.
=> add version strings for NC 10.2 and 11

controller/pagecontroller.php, templates/goto.tmpl.php
Fix #114 
This PR appends a counter to text poll entries. Thus there are no double values in the database (e.g. `tea_0`, `cake_1`, `tea_2`, ...). This doesn't work for existing polls, only for new polls. Hope this helps anyway. Please test @joergmschulz
=> append counter to text polls

js/vote.js
IE and Safari couldn't interprate the date format correctly. This patch correct the display on common browsers.
=> Fix date display in IE and Safari (NaN)

lib/Controller/PageController.php
Strict comparison failed and created polls, which always expired.
=> Strict comparison fix (PHP)

js/create_edit.js, lib/Controller/PageController.php, templates/create.tmpl.php
When entering an expiry date, the routines add 24 hours to target the end of the day. When displaying it again in the edit form, there are again 24 hours substracted. 
Because of the different timezones this may fail. The user enters a date regarding to his local timezone, which is also used by the js function, which writes this to the hidden fields, where the server respects the server time zone. 
Example: 
Field value 08.12.2017 (local tz)
DB says 2017-12-08 23:00:00 (server tz)
On loading: 07.12.2017 (DB entry/server tz - 24 hours)
The commit adds 23:59:59 to the date, regarding the local tz. and doues no more add or substract 24 hours. 
Example: 
Field value 08.12.2017 -> timestamp 08.12.2017 23:59:59 (local tz)
DB says 2017-12-08 22:59:59 (server tz)
On loading: 08.12.2017 (DB …
=> Change on calculating expiry time stamp

.travis.yml, lib/Migration/Version009000Date20171202105141.php
Also locked Nc repo from master to stable 13 for Travis CI.
=> Fixed Travis CI + https://github.com/nextcloud/server/pull/7909

css/vote.scss
We never use italic and it just is not very readable or well-looking:
Please review @nextcloud/designers @nickvergessen @MorrisJobke @dartcafe
=> Remove italic styling for winner entries, bold is enough

lib/AppInfo/Application.php, lib/Controller/PageController.php, tests/Unit/Controller/PageControllerTest.php
> ![bildschirmfoto von 2018-11-15 22-31-54](https://user-images.githubusercontent.com/213943/48583123-a0c38f80-e926-11e8-8929-30922e75a05a.png)
I simplified the text of the email a bit.
Feel free to extend it again, but I think it's good and simple enough.
Alternative text I would suggest is:
* addHeading (black text on grey): `<title of poll>`
* addBodyText (grey text on white): `<user name> participated/voted`
* addBodyButton (white text on blue): `Go to poll`
Fix #178 
Fix #419
=> Use the email templating and use the language of the recipient

appinfo/info.xml
Fixes #421 
I gave it a test and all seems to work. Should I also raise the version number so you could release 0.9.1 or something like that in the appstore to make it available to beta testers that are already updating to Nextcloud 15 beta 2?
=> Allow Nextcloud 15

appinfo/info.xml
This is necessary to make the Polls app work on the current master / dev version of Nextcloud which is version 16. :)
Please review @dartcafe @splitt3r @v1r0x
=> Update max-version to current dev version 16

templates/main.tmpl.php
On an empty main site, the link to poll creation on the middle of the page is broken when nextcloud is running on a subfolder.
This PR fixes this by using the same link as used for the + button in the breadcrumb bar.
=> fix link to create poll on empty main site

css/list.scss
Hi, I noticed the variable name --text-maxcontrast has been used. This variable hasn't actually been defined anywhere, so I have changed it to the variable name used by nextcloud server.
=> Fix color variable name in list.scss

lib/Db/EventMapper.php
The `findAll` query requires no params, thus `['*']` throws an error. This PR simply removes the param.
=> Fix query params in eventmapper

lib/Db/NotificationMapper.php
I get the following exception when storing votes with email notifications disabled:
```
Argument 1 passed to OCP\AppFramework\Db\QBMapper::delete() must be an instance of OCP\AppFramework\Db\Entity, array given, called in …/apps/polls/lib/Controller/PageController.php on line 328
```
The fix seems obvious, since the function `findByUserAndPoll()` in `NotificationMapper` does in fact return an array, which is inconsistent with its documentation and its callers.
=> Fix TypeError exception

src/js/components/SideBar/SideBarOnlyComments.vue, src/js/views/Vote.vue
Workaround for nextcloud/nextcloud-vue/issues/747 with an ugly animation. Prevents displaying wrong tabs, when user ha (no) edit rights. Otherwise a sidebar wth empty or missing tabs is rendered and maybe confusing to normal users.
=> Load different sidebar when user has (no) edit rights

src/js/components/Comments/CommentAdd.vue
I simplified the comment form by removing the duplicate `writeComment` call.
`@submit` on form is triggered when
1. clicked on button with `type="submit"`
2. hit enter in an input field
=> use submit event of form to add a comment

src/js/components/VoteTable/VoteHeaderPublic.vue
Using "username" like on > 200 strings over the whole Nextcloud project.
=> l10n: Changed spelling of "user name" to "username"

src/js/components/Base/ButtonDiv.vue, src/js/components/SideBar/SideBarTabConfiguration.vue, src/js/components/SideBar/SideBarTabOptionsDate.vue, src/js/components/SideBar/SideBarTabShare.vue, src/js/components/VoteTable/VoteHeaderPublic.vue, src/js/main.js, src/js/views/Vote.vue
=> Public link cursor and Autofocus name field in public vote

appinfo/routes.php, lib/Controller/VoteController.php, src/js/components/Base/UserDiv.vue, src/js/components/VoteTable/VoteHeaderPublic.vue, src/js/components/VoteTable/VoteTable.vue, src/js/store/modules/votes.js
=> Remove users from a poll

lib/Controller/PollController.php, lib/Controller/ShareController.php, lib/Controller/SystemController.php, lib/Controller/VoteController.php, lib/Model/Acl.php, lib/Service/MailService.php, src/js/components/Base/UserDiv.vue, src/js/components/SideBar/SideBarTabShare.vue, src/js/components/VoteTable/VoteHeaderPublic.vue, src/js/store/modules/shares.js, src/js/views/Vote.vue
fix #822 
Enter email address and select the user
Email is sent out to some.user@foo.com
After the user enters a username, the share type is updated from email invitation to external share.
The initial share token stays valid.
=> Share poll via email #822

package.json, src/js/components/SideBar/SideBarTabConfiguration.vue, src/js/components/SideBar/SideBarTabOptionsDate.vue
* fixed setting of expiration date 
* updated @nextcloud/vue to latest version (1.4.1) at least for security fixes
* updated date-picker options to new format (vue2-datepicker 3.4.1, which came with @nextcloud/vue 1.4.1)
* switched to `minuteStep: 1` fixes #826
* Changed picker layout
=> [1.4.0 beta1] Fix datetimepicker

lib/Controller/VoteController.php, lib/Db/VoteMapper.php, lib/Model/Acl.php, src/js/components/Base/PollInformation.vue, src/js/components/SideBar/SideBarTabConfiguration.vue
resolves #265 
Added "Show results" to configuration:
* always
* after poll expiration
* never
The poll owner will see the results always and the participants get an information, that the result is hidden.
=> hide results

src/js/components/Navigation/NavigationSettings.vue, src/js/components/VoteTable/VoteTable.vue, src/js/components/VoteTable/VoteTableHeaderItem.vue, src/js/store/modules/settings.js, src/js/views/Vote.vue
fix #744 
Define the default view for text and date polls
* The initial default setting for text polls is now mobile view (list layout)
* The initial default setting for date polls is now desktop view (table layout)
* The user can define his preffered setting
* Changing the view mode is possible und is kept for the poll type, when switching between polls
* initial setting on mobile layout is mobile view, regardless what default is set
=> Default view for poll types

lib/Db/PollMapper.php, lib/Service/PollService.php
fix #1181 
An attempt:
* when loading polls, skip polls which are marked as deleted and where the user is not owner of this poll
=> fix #1181 - do not unnecessarily load deleted polls

lib/Db/ShareMapper.php
remove existing shares with `user_id === null` or empty `type`
fixes #1376 
fixes #1377
=> remove invalid entries from polls_share

lib/Controller/PublicController.php, lib/Db/Option.php, lib/Db/Poll.php, lib/Migration/Version0108Date20210207134703.php, lib/Model/Acl.php, lib/Service/CommentService.php, lib/Service/OptionService.php, lib/Service/VoteService.php, src/js/components/Base/Confirmation.vue, src/js/components/Options/OptionsDate.vue, src/js/components/Options/OptionsText.vue, src/js/components/SideBar/SideBarTabConfiguration.vue, src/js/components/VoteTable/VoteItem.vue, src/js/components/VoteTable/VoteTable.vue, src/js/mixins/watchPolls.js, src/js/store/modules/options.js, src/js/store/modules/poll.js, src/js/store/modules/votes.js
Some tests showed, that the blocking of options is not possible if an OptionLimit is set and the results are hidden, because the frontend misses information to apply the logic
* moved the calculation of votes per option to the backend
* moved rank determining to backend
* load optoins and votes in watchPoll, if poll configuration, options or votes were affected
* added a configuration option to hide booked up options to the voters.
=> added hide options if booked out and move some logic to backend

Makefile, tests/bootstrap.php, tests/phpunit.xml
I could not get the tests to run correctly, but at least now the tests run. Fixes #1387 
In my case, they fail with `Error: Class 'OC' not found`, even when placed in the `apps` directory of an active Nextcloud installation. Could anyone point me to how to properly run the tests, or where the app should be placed to run these tests?
=> Fix test execution paths

src/js/store/modules/polls.js
The word "in which" is more appropriate.
=> l10n: Change "where" to "which"

lib/Service/ShareService.php, src/js/components/Poll/PublicRegisterModal.vue
Should fix #1559, if mail can't be sent out. 
* Log error 
* Show a different error toast to the user
* Do not prevent entering poll
=> Catch email send errors on registration to public poll

src/js/components/Poll/PublicRegisterModal.vue, src/js/components/Shares/SharesPublic.vue
fixes #587
Add url Parameters
* name=John Doe
* email=johndoe@example.com
will be used to prefill the fields in the registration dialog for public polls
Example
* `https://example.com/s/aUubZAvweQ6PaX2?name=John Doe&email=jondoe@example.org` or
* `https://example.com/s/aUubZAvweQ6PaX2?name=John%20Doe&email=jondoe%40example.org`
=> Allow URL-Parameters for username and email address in public share

lib/Model/Contact.php
=> Workaround: Don't throw error when contact UID is found multiple times

CHANGELOG.md, appinfo/info.xml, lib/Migration/Version0010Date20191227063812.php, lib/Migration/Version0104Date20200314074611.php, lib/Migration/Version0105Date20200523142076.php, lib/Migration/Version0106Date20201031080745.php, lib/Migration/Version0107Date20201210204702.php, lib/Migration/Version0107Date20201210213303.php, lib/Migration/Version0107Date20201217071304.php, lib/Migration/Version0107Date20210121220707.php, lib/Migration/Version0108Date20210307130003.php, package-lock.json
Details: 
* this version is identically to version 1.9.6 (downgrade)
* only compatible with Nextcloud 20 and 21
* No changes to the database
Additionally change to prevent #1723, since the migrationService doesn't allow `notNull=true` and `default='' anymore`.
To update the polls version manually: 
* disable polls
* delete `../apps/polls` in your Nextcloud installation
* extract the contents of the package (after it is available) to `../apps` in your Nextcloud installation, You should find a fresh created folder `polls`in your `apps` folder
* enable polls
Theoretically anything should work
=> Fix/branch stable1.9

src/js/components/Actions/ActionCopyMailAdresses.vue, src/js/components/Poll/ParticipantsList.vue, src/js/components/Poll/PollInformation.vue, src/js/components/VoteTable/VoteTable.vue, src/js/store/modules/poll.js, src/js/store/modules/votes.js, src/js/views/Vote.vue
related to #1643 and #1450
Vue can get knocked out, if too many component copies are generated. With a lot of options and participants, a poll table can grow to many thousend cells. A current use case showed some 125 participants with over 60 entries; Resulting in a table with more than 7.500 cells. 
The app gets really unusable, freezes the browser window/tab and crashes due to too many recursions (`too much recursion`). So a workaround is implemented which hides all votes but the votes of the current user, if the number of calsulated cells crosses a threshold of 200 cells. 
This current implementation is just a workaround, further investigation and another strategy for displaying huge tables must be found.
=> hide vote table if too many cells are predicted

lib/Listener/OptionListener.php, lib/Listener/PollListener.php, lib/Listener/VoteListener.php, src/js/App.vue, src/js/components/Comments/Comments.vue, src/js/mixins/watchPolls.js, src/js/router.js, src/js/views/Navigation.vue, src/js/views/SideBar.vue
* Load navigation and sidebar async via router
* Refresh poll list only, if navigation is loaded (this irrelevant in public polls, so avoid uneccessary request)
* decide dependent objects (options, votes) in servide listeners
=> Convert navigation and sidebar to views

src/js/assets/scss/hacks.scss, src/js/components/Poll/PublicRegisterModal.vue
fix #1855
* force scroll for registration dialog
* reduce padding, if media break < 688px (mobile)
=> Registration not scrollable

lib/Cron/JanitorCron.php, lib/Db/PollMapper.php, lib/Model/AppSettings.php, lib/Service/SettingsService.php, src/js/components/Settings/AdminMisc.vue, src/js/store/modules/appSettings.js
=> Autoarchive closed polls

src/js/components/Options/OptionItem.vue
quick fix #1981 
The calculation of full day events has changed, but there is work to do for the both days in the year, when daylight saving changes. In these cases the event duration is 23 or 25 hours. 
There is also an impact when shifting options over these dates.
=> Changed calculation of whole day events.

lib/Service/ActivityService.php, lib/Settings/ActivityVote.php
Reported by the user from Transifex.
=> l10n: Correct spelling

package-lock.json, package.json
Remove direct devDependencies, which are already loaded as peer dependency from @nextcloud/eslint-config
=> remove devDependencies from package.json

src/js/assets/scss/icons-dark.scss, src/js/assets/scss/icons.scss, src/js/components/Poll/PollInformation.vue, src/js/components/PollList/PollItem.vue, src/js/components/PollList/PollItemAdmin.vue, src/js/components/Settings/AdminSettings/AdminShareSettings.vue, src/js/components/Shares/ShareItemAllUsers.vue, src/js/components/User/UserItem.vue, src/js/store/modules/polls.js
=> rename public and hidden polls to open and private

lib/Model/Mail/MailBase.php, lib/Service/MailService.php, lib/Service/PollService.php, src/js/components/Export/ExportPoll.vue, src/js/components/User/UserMenu.vue
=> add email addresses to poll export for owner

src/js/components/Activity/ActivityItem.vue, src/js/components/Base/RadioGroupDiv.vue, src/js/components/Calendar/CalendarInfo.vue
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
=> Replace deprecated String.prototype.substr()

lib/Model/Mail/InvitationMail.php
fixes #2306
Add plain poll description for plain text email configuration
=> use plain description if config is  'mail_send_plaintext_only' #2306

CHANGELOG.md, src/js/components/Poll/PublicRegisterModal.vue, src/js/helpers/arrayHelper.js, src/js/helpers/cookieHelper.js, src/js/helpers/detectColorScheme.js, src/js/router.js, src/js/store/modules/share.js
For a better UX a public user can decide, if he wants to keep the private token for a public poll in a cookie.
The cookie expiry is currently set to 30 days and will get renewed after every access.
=> store personal token for a public poll in a cookie

src/js/App.vue, src/js/assets/scss/theming.scss, src/js/components/Poll/PollHeaderButtons.vue, src/js/store/modules/settings.js, src/js/views/Vote.vue
Affects mostly the experimental design settings.
=> refactor and fix styling

lib/Service/ActivityService.php, src/js/components/Activity/ActivityItem.vue, src/js/helpers/GuestBubble.js
* UserBubble doesn't support guest
* Avoid console errors while trying to load avatars of guests
* Catch Exception in background job
=> fix small issues in relation to activities

lib/Controller/AdminController.php, lib/Controller/CommentApiController.php, lib/Controller/CommentController.php, lib/Controller/OptionApiController.php, lib/Controller/OptionController.php, lib/Controller/PageController.php, lib/Controller/PollController.php, lib/Controller/PreferencesController.php, lib/Controller/PublicController.php, lib/Controller/SettingsController.php, lib/Controller/ShareApiController.php, lib/Controller/ShareController.php, lib/Controller/SubscriptionController.php, lib/Controller/VoteController.php, lib/Controller/WatchController.php, lib/Db/Comment.php, lib/Db/Option.php, lib/Db/Vote.php, lib/Model/Acl.php, lib/Model/UserGroup/UserBase.php, lib/Service/AnonymizeService.php, lib/Service/CommentService.php, lib/Service/OptionService.php, lib/Service/PollService.php, lib/Service/ShareService.php, lib/Service/SubscriptionService.php, lib/Service/VoteService.php, lib/Service/WatchService.php, src/js/store/modules/subModules/acl.js
Currently the public displayname is identical with the displayName, which does not allow a public user to change his name. 
* generate unique userId for public users
* keep displayName separated from userId
* allow using userId of current public user while hiding other's userIds
relates #2400
=> Separate public userId from displayName

appinfo/info.xml, appinfo/routes.php, lib/AppInfo/Application.php, lib/Command/Poll/TransferOwnership.php, lib/Controller/PollApiController.php, lib/Controller/PollController.php, lib/Db/PollMapper.php, lib/Event/PollOwnerChangeEvent.php, lib/Listener/BaseListener.php, lib/Service/PollService.php, psalm-baseline.xml
* Transfer ownership of all polls of one user to another user
* adding occ command to move all polls from a user to another
* `occ polls:poll:transfer-ownership {sourceUser} {targetUser}`
* adding API endpoint
* `/apps/polls/api/v1.0/polls/transfer/{sourceUser}/{targetUser}`
fix #2297
occ ouput as followed: 
```
This command will change the ownership of all polls of {sourceUser} to {targetUser}.
NO notifications will be sent to the users.
Continue with the transfer (y/n)? [n] y
7 polls were transferred from {sourceUser} to {targetUser}
* 1 - poll title of id 1
* 6 - poll title of id 2
...
```
=> Transfer ownership

src/js/components/Comments/CommentItem.vue, src/js/components/Comments/Comments.vue, src/js/components/Settings/UserSettings/StyleSettings.vue, src/js/store/modules/settings.js
Added an alternive personal styling setting for the comments sidebar
Please that the styling settings are still experimental and can be removed at any time.
|         | inactive | active |
|--|--|--
dark | ![grafik](https://user-images.githubusercontent.com/26707476/179819184-3997f6ea-dd30-4d24-8028-e0fd64831d92.png) | ![grafik](https://user-images.githubusercontent.com/26707476/179819216-3a386228-72ed-4d5f-ba60-8742a4f7043b.png) |
light | ![grafik](https://user-images.githubusercontent.com/26707476/179819861-1fecd216-c9e5-40ea-8ab8-111c49b3e538.png) | ![grafik](https://user-images.githubusercontent.com/26707476/179819883-e5058f4b-2aed-43ae-8baa-9903c8c3fe66.png)
=> experimental comment styling

lib/Controller/OptionController.php
Closes #2560 
Tested with NC23.0.8 & PHP 8.0 
This change allowed a non-admin user to use the 'paste option list' feature. 
Signed-off-by: EngelPika32 <41995155+EngelPika32@users.noreply.github.com>
=> Fix: addBlulk endpoint no longer requires admin

appinfo/info.xml, src/js/assets/scss/colors-dark.scss, src/js/assets/scss/colors.scss, src/js/assets/scss/hacks.scss, src/js/assets/scss/theming.scss, src/js/views/Combo.vue, src/js/views/Vote.vue
* change css due to new css variables since NC25
* handle prefer-color-scheme in public polls and new apperance setting
ref https://github.com/nextcloud/server/issues/32060
=> Fix darkmode in NC25+

src/js/views/SideBar.vue
Revert https://github.com/nextcloud/polls/pull/2585 as `master` targets NC24
Handing off to @dartcafe to revert this revert when `master` targets NC25
=> Revert "Merge pull request #2585 from nextcloud/enh/hide-projects-2"

lib/Controller/PublicController.php, lib/Db/Comment.php, lib/Db/Log.php, lib/Db/Option.php, lib/Db/Poll.php, lib/Db/Preferences.php, lib/Db/Share.php, lib/Db/Subscription.php, lib/Db/Vote.php, lib/Db/Watch.php, lib/Model/Settings/AppSettings.php
* surpress error logs with PHP 8.1 by changing return type of `jsonSerialize()` to `: array`
`Error: Return type of [...]::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at [...]`
* fix permission on voting in public polls, whan comments are disabled
fix #2600
=> Fixes for Version 3.8.1

lib/Db/Comment.php, lib/Db/EntityWithUser.php, lib/Db/IEntityWithUser.php, lib/Db/Option.php, lib/Db/Poll.php, lib/Db/Share.php, lib/Db/ShareMapper.php, lib/Db/Vote.php, lib/Exceptions/ShareNotFoundException.php, lib/Model/Acl.php, lib/Model/Mail/NotificationMail.php, lib/Provider/ActivityProvider.php, lib/Service/AnonymizeService.php, lib/Service/PollService.php, lib/Service/ShareService.php, lib/Service/UserService.php
* Generally change name of unidentifyable users to 'Deleted User'
* Hash userId instead of replacing with displayname in public polls
fixes #2636
=> Change handling of objects which refer to deleted shares

.github/workflows/phpunit.yml, lib/Db/Comment.php, lib/Db/EntityWithUser.php, lib/Db/IEntityWithUser.php, lib/Db/Option.php, lib/Db/Poll.php, lib/Db/Share.php, lib/Db/ShareMapper.php, lib/Db/Vote.php, lib/Exceptions/ShareNotFoundException.php, lib/Model/Acl.php, lib/Model/Mail/NotificationMail.php, lib/Provider/ActivityProvider.php, lib/Service/AnonymizeService.php, lib/Service/PollService.php, lib/Service/ShareService.php, lib/Service/UserService.php
* Generally change name of unidentifyable users to 'Deleted User'
* Hash userId instead of replacing with displayname in public polls
Backport of #2640 instead of #2643
fixes #2636
=> Change handling of objects which refer to deleted shares (#2640)

lib/AppInfo/Application.php, lib/Dashboard/PollWidget.php, src/js/assets/scss/dashboard.scss, src/js/init-dashboard.js, src/js/views/Dashboard.vue, webpack.config.js
I developed a simple dashboard widget for personal use. I guess it doesn't hurt to share it with the community!
Note: I can take some feedback into account, but I might not be very active on this PR. If anyone wants to take over the PR to improve / fix / ... feel free
=> Dashboard widget to list relevant polls

lib/Service/NotificationService.php
I have an issue very similar to https://github.com/nextcloud/polls/issues/2133 in 3.8.3.
Since we're in a cron job the `$UserId` constructor argument isn't provided with a value, and can't be used.
Side note: The `$UserId` auto-injection is now deprecated in favor of `$userId` https://github.com/nextcloud/server/pull/34929
```
TypeError: Argument 1 passed to OC\Notification\Notification::setUser() must be of the type string, null given, called in /var/www/nextcloud/apps/polls/lib/Service/NotificationService.php on line 51 and defined in /var/www/nextcloud/lib/private/Notification/Notification.php:154
Stack trace:
#0 /var/www/nextcloud/apps/polls/lib/Service/NotificationService.php(51): OC\Notification\Notification->setUser()
#1 /var/www/nextcloud/apps/polls/lib/Notification/Notifier.php(12 …
```
=> Handle userid being null in NotificationService

lib/Cron/JanitorCron.php, lib/Model/Settings/AppSettings.php, lib/Service/WatchService.php, src/js/store/modules/appSettings.js
Adding defaults to app settings
Fixing a bug, when no polling type was set and an infinite update call was sent to server.
=> add defaults to app settings

src/js/components/Poll/PublicRegisterModal.vue
`generateUrl()` from nextcloud/nextcloud-router ignores parameters.
fix #2812
=> temporarily fix redirect

README.md
The readme file states 
> Install dev environment with `make dev-setup`
but the Makefile states 
`# install deps for ci (tests and analysis)`
`setup-dev: setup-dev-composer npm-init`
=> fix readme dev setup

CHANGELOG.md, src/js/components/SideBar/SideBarTabConfiguration.vue
=> use NcNoteCard

src/js/assets/scss/hacks.scss, src/js/components/Base/BadgeDiv.vue, src/js/components/Comments/CommentItem.vue, src/js/components/Options/OptionsText.vue, src/js/components/PollList/PollItem.vue, src/js/views/Dashboard.vue
Explanation: the color-primary variables are not to be used in components because the introduce problems with high-contrast primary colors. Fix this by using the primary-element variables instead.
=> Use the color-primary-element* variables

lib/Db/OptionMapper.php, lib/Db/Poll.php, lib/Db/PollMapper.php, lib/Db/Preferences.php, lib/Db/TableManager.php, lib/Listener/BaseListener.php, lib/Migration/TableSchema.php, lib/Migration/Version050100Date20230515083001.php, lib/Service/PollService.php, src/js/components/Settings/UserSettings/FeatureSettings.vue, src/js/store/modules/polls.js, src/js/store/modules/settings.js
resolves #2909
* remove polls without recent interactions from relevant list
* let the user configure the offset for removal in days
* calculate threshold from creation date, expiry date, last interaction and latest date option
=> Remove old polls from relevant list

lib/Controller/OptionController.php, lib/Db/Option.php, lib/Db/OptionMapper.php, lib/Middleware/RequestAttributesMiddleware.php, lib/Service/CalendarService.php, lib/Service/OptionService.php, src/js/Api/HttpApi.js
Respect the client's timezone, when 
* creating a sequence of date options or
* when shifting all options
* added a http header to send the client's timezone
* mutate dates with the client's timezone
This will fix problems when mutating dates while crossing the daylight saving time borders
fixes #2625 
fixes #2850
=> Move and shift dates respecting client's timezone

CHANGELOG.md, lib/Controller/PreferencesController.php, lib/Cron/UserDeletedJob.php, lib/Db/Preferences.php, lib/Db/PreferencesMapper.php, lib/Db/TableManager.php, lib/Listener/UserDeletedListener.php, lib/Migration/RepairSteps/DeleteInvalidRecords.php, lib/Service/CalendarService.php, lib/Service/PollService.php, lib/Service/PreferencesService.php, src/js/Api/userSettings.js, src/js/store/modules/settings.js
fixes #2975
* use PreferencesService instead of PreferencesMapper
* always return default preferences when user not found
* persist preferences by first time usage of polls
=> Fix preferences

.github/BETA_NOTIFICATION.md, .github/RELEASE_NOTIFICATION.md, .github/actions/get-polls-version/action.yml, .github/workflows/publish_beta.yml, .github/workflows/publish_release.yml
* replace deprecated set-output
* don't create Releases as draft
* extract changelog for latest version
* create notification via workflow
=> automate releases and notification

appinfo/routes.php, lib/Controller/CommentApiController.php, lib/Controller/PollApiController.php, lib/Controller/ShareController.php, lib/Controller/SubscriptionApiController.php, lib/Controller/VoteApiController.php, lib/Service/OptionService.php, lib/Service/PollService.php, lib/Service/ShareService.php, src/js/Api/polls.js, src/js/store/modules/subscription.js
* Make sure all API Methods are running and routes are set correctly
* Preparation for Migration to OCSController
=> Fixing API

CHANGELOG.md, appinfo/routes.php, lib/Controller/ShareController.php, lib/Service/ShareService.php, src/js/Api/shares.js, src/js/components/Shares/ShareItem.vue, src/js/components/Shares/SharesList.vue, src/js/components/User/UserItem.vue, src/js/store/modules/shares.js
* add label for public shares
* move shares from shares list to shareItem component
=> Add label for public shares

src/js/Api/public.js
Deleting comments in the public URL does not work now.
=> Fix deleteComment url

src/js/components/Options/OptionsDate.vue
Fix `TypeError: can't access property "confirmed", this.option is undefined` on closed polls
=> remove console error

lib/Controller/PublicController.php, lib/Service/ShareService.php
Avoid label of public share from beeing used as intitial displayname
=> fix displayname in public registration

src/js/App.vue, src/js/components/Options/Counter.vue, src/js/components/Options/OptionItem.vue, src/js/components/Poll/PollInfoLine.vue, src/js/components/VoteTable/VoteTable.vue, src/js/views/SideBar.vue, src/js/views/Vote.vue
Some minor UX issues: 
* Give a hint, if the poll is not accesiable from anyone else but the owner.
* Unify the width of date polls, to be able to better differentiate between the poll options
* Introduce `text-wrap: balance;` for text polls (Not supported by all browsers) 
See https://caniuse.com/css-text-wrap-balance
* fix sidebar tab change
Hint for unpublished polls and unified column width| 
-|
=> Minor design improvements and hint for unpublished polls

lib/Service/SystemService.php
On Instances with many groups the validatePublicUsername endpoint ends with a timeout, because the code checking if the anonymous users chosen userName matches any group on the server is quite inefficient. It does not utilize the search parameter of the Group::search() function and therefore loads all groups from all group backends from the database into RAM, creates a php entity for every one of them and calls two functions on every one of those entities.
I created a performance profile of a simple call of the /check/username endpoint on an instance with ~12k groups (which is certainly a lot, but I assure you every one of those has an important role on our instance and other apps have no problems working with this amount of groups):
In total this request took 71.6 seconds, causing the …
=> improve validatePublicUsername() performance

CHANGELOG.md, appinfo/routes.php, lib/Controller/ShareApiController.php, src/js/components/Shares/ShareItem.vue, src/js/store/modules/shares.js
fixes after hints https://github.com/nextcloud/polls/issues/3107#issuecomment-1763406245
=> Forgotten changes

CHANGELOG.md, src/js/components/Poll/MarkUpDescription.vue, src/js/components/Poll/PollInfoLine.vue, src/js/components/Poll/PollInformation.vue, src/js/components/Public/PublicRegisterModal.vue, src/js/views/Vote.vue
* Changed user flow in case of public shares
By opening a poll with public share, the registration modal will not pop up automatically anymore. 
A new CTA has been added to open the registration dialog, also when it had been closed. 
This way a user has the chance to see the poll purpose, before the user decides to participate or not.
Additionally and finally it is now possible to reopen the registration dialog, after it has been closed.
resolves #3119
* Fixed cookie creation
=> Change user flow for public registration

lib/Migration/TableSchema.php
A bug has been introduced with https://github.com/nextcloud/polls/commit/3da60e4457c5100ccf9184a721a16317bffe1447 which is causing migration errors when you try to upgrade the app.
```
Database error when running migration 050100Date20230515083001 for app polls
An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "session_id" contains null values
```
Having a non-nullable column with the default value of `null` is definitely not right. likely introduced by mistake with the refactoring of the class.
In this PR, I have made the `session_id` column nullable which is the intended behavior.
I have also reviewed all other combinations on the file and found no other non-nullable columns with a default value of `null`.
This is not being reflected …
=> Not null violation error in migrations

lib/Model/CalendarEvent.php
fixes #3245
Just a quick fix to avoid error logging and fix calendar event parsing
TODO: properly parse sabre object.
=> Avoid error logging on parsing calendar events

CHANGELOG.md, lib/Service/WatchService.php
When entering poll lists, the WatchService tried to access a pollId 0
fixes #3330
=> Fix WatchService accessing pollId 0

CHANGELOG.md, lib/Model/User/Email.php, lib/Model/UserBase.php, src/js/components/User/UserSearch.vue
This partially fixes #3335 for plain mail addresses. 
Email notations like "John \<john@foo.com>" is still broken. Wait for the outcome of https://github.com/nextcloud-libraries/nextcloud-vue/issues/5293
=> Partially fix email shares

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
When creating #3345 I noticed that some PHP and Nextcloud options can't be picked as an option in the issue template
=> update issue template for newer PHP and Nextcloud versions

.github/workflows/codeql-analysis.yml, lib/Service/SystemService.php
Remove a range from unicode characters from usernames when validating allowed usernames
=> strip some unicodes from public username

lib/AppInfo/Application.php, lib/Controller/PollController.php, lib/Cron/JanitorCron.php, lib/Db/Poll.php, lib/Db/PollMapper.php, lib/Db/Share.php, lib/Db/VoteMapper.php, lib/Helper/Container.php, lib/Model/Acl.php, lib/Model/Settings/AppSettings.php, lib/Model/UserBase.php, lib/Service/SettingsService.php, lib/Service/WatchService.php, package-lock.json, tests/Unit/Db/CommentMapperTest.php, tests/Unit/Db/LogMapperTest.php, tests/Unit/Db/OptionMapperTest.php, tests/Unit/Db/PollMapperTest.php, tests/Unit/Db/SubscriptionMapperTest.php, tests/Unit/Db/VoteMapperTest.php
Count current user's votes via join in poll
regarding #3362
=> join votes for participation check

lib/Db/CommentMapper.php, lib/Db/OptionMapper.php, lib/Db/PollMapper.php, lib/Db/Preferences.php, lib/Db/QBMapperWithUser.php, lib/Db/ShareMapper.php, lib/Db/VoteMapper.php, tests/Unit/Db/PollMapperTest.php
fixes #3393 
* added `testFind` to unit tests
* adding and maintaining grouping statements
=> fix PollMapper for PostgreSQL usage

CHANGELOG.md, src/js/components/Navigation/PollNavigationItems.vue, src/js/views/PollList.vue
see also warnings issue in #3413
=> bring back archive, restore and delete actions

CHANGELOG.md, lib/Model/Group/Group.php
=> extract keys insted of wrong usage of key()

lib/Model/Mail/NotificationMail.php, lib/Model/User/GenericUser.php, lib/Provider/ActivityProvider.php, src/js/components/Base/modules/FlexSettings.vue, src/js/components/Cards/modules/CardLimitedVotes.vue, src/js/components/Options/OptionsDateShift.vue, src/js/components/Public/PublicRegisterModal.vue, src/js/components/Settings/AdminSettings/AdminActivities.vue, src/js/components/Settings/AdminSettings/AdminArchivePolls.vue, src/js/components/Settings/AdminSettings/AdminCombo.vue, src/js/components/Settings/AdminSettings/AdminEmail.vue, src/js/components/Settings/AdminSettings/AdminLegal.vue, src/js/components/Settings/AdminSettings/AdminPerformance.vue, src/js/components/Settings/AdminSettings/AdminPollCreation.vue, src/js/components/Settings/AdminSettings/AdminPollDownload.vue, src/js/components/Settings/AdminSettings/AdminShareOpenPoll.vue, src/js/components/Settings/AdminSettings/AdminSharePublicCreate.vue, src/js/components/Settings/AdminSettings/AdminSharePublicShowLogin.vue, src/js/components/Settings/AdminSettings/AdminShowMailAddresses.vue, src/js/components/Settings/UserSettings/PerformanceSettings.vue, src/js/components/Settings/UserSettingsDlg.vue, src/js/components/Shares/ShareItem.vue, src/js/components/SideBar/SideBarTabOptions.vue, src/js/components/User/UserItem.vue, src/js/components/VoteTable/VoteTable.vue, src/js/views/AdminSettingsPage.vue, src/js/views/Administration.vue, src/js/views/Navigation.vue, src/js/views/PollList.vue, src/js/views/UserSettingsPage.vue
* changing disallow to enable in admin section to correspont to switches
* updated strings naming participants where meaningful
* slightly rearranged admin settings
=> updated strings and rearrangement of admin settings

lib/Db/UserMapper.php, lib/Model/Acl.php, lib/Service/PollService.php
Trying to bring the number of DB requests for polls listing down.
So far got down from 52 to 30 for 4 polls with no votes.
=> Perf improvements for stable-6 for 26 branch

src/js/store/modules/polls.js, src/js/views/PollList.vue
=> fix: Add visual loading feedback for polls list

lib/Db/Poll.php, lib/Db/PollMapper.php, lib/Db/VoteMapper.php
=> [stable-6] Count user's votes by subquery

lib/Service/PollService.php, src/js/components/Configuration/ConfigAutoReminder.vue, src/js/components/Export/ExportPoll.vue, src/js/components/Navigation/PollNavigationItems.vue, src/js/components/Options/OptionsText.vue, src/js/components/Options/OptionsTextAddBulk.vue, src/js/components/Shares/ShareItem.vue, src/js/components/Shares/SharePublicAdd.vue, src/js/components/User/UserMenu.vue, src/js/store/modules/polls.js, src/js/views/Administration.vue, src/js/views/Dashboard.vue, src/js/views/Navigation.vue, src/js/views/PollList.vue
* remove polls without view access from returned list
* fix store mapping preventing poll cloning
* add ariaLabels to NcActionButtons
Missing aria label warning is thrown, if NcAction contains only one item
=> Fix poll list content

.github/workflows/phpunit.yml, .github/workflows/static-analysis.yml, CHANGELOG.md, appinfo/info.xml, composer.json, lib/Db/TableManager.php, lib/Migration/TableSchema.php, lib/Migration/Version060100Date20240209073304.php
Rely on the PHP 8.0 compatibility and avoid forcing devtools being compatible with PHP 8.0.
The PHPUnit fails, due to locked dev tools that rely on PHP >= 8.1. So tests with PHP8.0 got removed.
=> Support NC27

src/js/components/Activity/ActivityItem.vue
| b | a |
|--------|--------|
| <img width="461" alt="image" src="https://github.com/nextcloud/polls/assets/40746210/14c9b3e6-b4b1-47d0-a8ae-e084fb6061be"> | <img width="461" alt="image" src="https://github.com/nextcloud/polls/assets/40746210/485bfbc2-69e2-4475-b1e4-1b3713ce059b"> |
=> fix: Display circle share activities correctly

lib/Service/MailService.php
Previously when constructor would throw, it would stop there and on the
next run the notifications before the broken one would get resent.
Exceptions from constructor are now caught and the process continues.
=> fix: Catch exceptions thrown by NotificationMail constructor

.github/workflows/appstore-build-publish.yml
This workflow will be used to build packages at https://github.com/nextcloud-releases/polls
=> ci: Add release automation workflow

src/js/components/Cards/VoteInfoCards.vue
Reproduction:
1. Create a poll with a few options 
2. Share poll by mail 
3. open the share link received in the email 
4. Vote 
5. Register with the same email 
**Desired behaviour :** 
The new display name gets updated in the vote results 
**Actual behaviour :**
The vote is displayed as deleted user
=> fix : deleted user when email share registers

lib/Service/WatchService.php
=> fix: pollId equals 0

src/js/helpers/modules/cookieHelper.js
I noticed after loging out from a public share sometime a space character gets added to the token -> route which causes a 404  
I'm still not sure why it happens and it doesn't look deterministic, I'm still investigating 
Notice the extra space in the following screenshots
=> fix: space in token causes 404 on logout

lib/Controller/VoteController.php, lib/Service/OptionService.php, lib/Service/VoteService.php, src/js/components/VoteTable/VoteItem.vue, src/js/store/modules/votes.js
Without this you can run into this bug
=> fix: disable vote option while loading

CHANGELOG.md, appinfo/info.xml, lib/Command/Db/Rebuild.php, lib/Db/IndexManager.php, lib/Service/PreferencesService.php, lib/Service/WatchService.php
**This is a hotfix** to address a particular problem with heavy and expensive index recreation on large databases.
relates #3679 but not final fix
backlink to #3689 for transparancy
Problem description: 
At least one known instance with a large amount of polls and votes, etc. suffers from the recreation of indices, because it slows down the database after every update. Oviously the database discards existing execution plans and in the result, the database slows down until the execution plans are optimized again. 
This is the problem how I understood it. Correction are welcome. 
A quick analysis of the current code reveals, that it is safe to keep the index creation, since existing indices seem to stay untouched. This affects unique and other indices (check for existing indices already …
=> Avoid expensive index recreation

lib/Db/Share.php, lib/Service/ShareService.php
Explanation of this fix, which should be appied to #3714 first.
The cause of this behavior is #3125. This change removed the initial registration dialog after entering a poll via share token. The dialog was meant to allow participants 
* to register while using a public share token and create a personal share and 
* to check user parameters (mail and displayname) using an email or contact share. 
The second use case was eliminated with the issue causing PR. The result was, that the share type stays the initial type. 
This PR now converts theese shares into external sharesm by changing the type and replacing the userId by a generated one, to make sure, sensitive informations get removed (like mail address in email shares).
=> Convert email and contact shares to external shares on first usage

lib/Db/Share.php, lib/Service/ShareService.php, src/js/components/User/UserMenu.vue
Steps to reproduce:
1. Create a poll with some options
2. Go to share tab and share vial mail
3. Open the poll with that share link
4. open the settings 
5. seem them turn green
6. Hit the fields' save arrow at the right
7. `Displayname can only be set for external shares.`
=> fix: show edit inputs only for external shares

lib/Db/CommentMapper.php, lib/Db/OptionMapper.php, lib/Db/VoteMapper.php, lib/Service/ShareService.php
Rename userId as a follow up on renaming a share's userId 
This covers the situation, where a userId of a share is changed, but there are already existing votes, comments  or options belonging to the renamed user.
This situation could occur, if a user already registered before the update to 7.2.4 and 
already voted, commented or suggested an option and reenters the poll with an email or contact share
Follow up to #3716
=> fix aftermath of #3716

src/components/User/UserMenu.vue
=> [next] fix: show edit inputs only for external shares

lib/Controller/ShareController.php, lib/Model/Settings/AppSettings.php, lib/Service/MailService.php, lib/Service/SettingsService.php, src/Api/modules/shares.js, src/components/Base/modules/InputDiv.vue, src/components/Comments/CommentAdd.vue, src/components/Configuration/ConfigOptionLimit.vue, src/components/Configuration/ConfigVoteLimit.vue, src/components/Settings/AdminSettings/AdminCombo.vue, src/components/Settings/AdminSettings/AdminPollCreation.vue, src/components/Settings/AdminSettings/AdminPollDownload.vue, src/components/Settings/AdminSettings/AdminShareOpenPoll.vue, src/components/Settings/AdminSettings/AdminSharePublicCreate.vue, src/components/Settings/AdminSettings/AdminShowMailAddresses.vue, src/components/Shares/SharePublicAdd.vue, src/components/User/UserSearch.vue, src/stores/shares.ts
misc fixes regarding inputs and ncSelect
=> more fixes and optimizations after tests

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/actions/setup-composer/action.yml, .github/actions/setup-server/action.yml, .github/workflows/phpunit.yml, .github/workflows/static-analysis.yml, lib/Db/Comment.php, lib/Db/EntityWithUser.php, lib/Db/Log.php, lib/Db/Option.php, lib/Db/Poll.php, lib/Db/Preferences.php, lib/Db/Share.php, lib/Db/Subscription.php, lib/Db/Vote.php, lib/Db/Watch.php
=> [Actions] update versions

lib/Db/Poll.php, lib/Db/PollMapper.php
Backport from `next`  (cherry-pick 878e35b)
fix #3761
=> Backport shorten column names from next (878e35b)

lib/Model/UserBase.php, src/js/components/User/UserSearch.vue
Searching for users to share with by email was broken.
This is due to 2 problems:
1. The subname key for users had the wrong casing `subName` instead of `subname`
2. The frontend filtering was active despite not being needed as backend already returns a filtered list
Before  | After
------------- | -------------
@dartcafe Is it safe to rename subName to subname or is used elsewhere? The only instance I could find is https://github.com/nextcloud/polls/blob/master/src/js/store/modules/acl.js#L16 and it looks pretty safe to rename if needed.
=> Fix user search by email

lib/Controller/VoteController.php, lib/Service/VoteService.php, src/components/VoteTable/VoteItem.vue, src/stores/votes.ts
relates #3752 for next branch
manual backport of #3821
=> Fix limit check

lib/Service/VoteService.php, src/js/components/VoteTable/VoteItem.vue, src/js/store/modules/votes.js
=> fix vote limit check

src/composables/context.ts, src/router.ts, src/stores/session.ts
A race condition could raise errors, where the user object is loaded too late and after following objects
=> avoid race condition on context loading

src/js/components/User/UserSearch.vue
=> fix: Remove dropdown options limit from sharing search

src/components/User/UserSearch.vue
=> [next] fix: Remove dropdown options limit from sharing search

lib/Model/Acl.php, lib/Model/Settings/AppSettings.php, lib/Model/User/User.php, lib/Model/UserBase.php, lib/Service/ShareService.php, lib/Service/SystemService.php, src/js/components/Shares/SharesList.vue, src/js/components/SideBar/SideBarTabShare.vue, src/js/store/modules/acl.js
Alternative implementation of #3893
For reviewers and testers, please check the checkboxes, if the functionality can be approved. I could confirm the functionality so far. After approval, I will merge and build version 7.4.
Summary: 
Additionally 
External shares in this context are
* public links
* email shares
* contacts and contact groups
Circles (teams) will still be allowed, but external users are skipped, if the Circle (team) gets resolved. 
Note: Polls still uses the term Circle
=> Apply core share group restrictions

lib/Controller/PollController.php, lib/Cron/JanitorCron.php, lib/Db/EntityWithUser.php, lib/Db/Share.php, lib/Helper/Container.php, lib/Model/UserBase.php
Decision to keep the abstraction layer ATM
Added a quick logger for testing purposes, to avoid the necessity of full LoggerInterface declaring
=> keep Container abstraction

README.md, appinfo/info.xml
The polling service by the TU Dresden, formerly known as dudle, as been renamed to DuD-Polls, due to a request by Doodle
> Warum wurde Dudle zu DuD-Poll umbenannt?
>
> Anfang 2022 gab es eine Aufforderung von Doodle, den Dienst umzubenennen. Wir haben weder Zeit noch Interesse an einer rechtlichen Auseinandersetzung.
https://dud-poll.inf.tu-dresden.de/about.cgi
this pull request so far only contains changing this name in appinfo/info.xml and the readme.
what is the best way to handle all the l10n files?
=> Updating 'dudle' name

lib/Controller/PublicController.php, lib/Model/Settings/AppSettings.php, lib/Service/SettingsService.php, src/components/Base/modules/InputDiv.vue, src/components/Public/PublicRegisterModal.vue, src/components/Settings/AdminSettings/AdminLegal.vue, src/stores/appSettings.ts
* Added a configuration setting to use the default terms (default is enabled) and 
* activate the footer for public polls
* change display of the link to the privacy policy and removed the text about accepting them
fixes #3895
. |Setting | Apperance
-|-|-
footer enabled| ![grafik](https://github.com/user-attachments/assets/f71ceaa3-dd9d-403b-b174-0313a4fa9e7b) | ![grafik](https://github.com/user-attachments/assets/93e26b57-f5a3-4ba7-9b30-eb0186be9ab2)
footer disabled| ![grafik](https://github.com/user-attachments/assets/506e4289-1d9a-4433-a12b-2773b55485a4)| ![grafik](https://github.com/user-attachments/assets/5bb9eb7b-fd1b-4108-a05f-88b1772fbd7a)
* With disabled footer alternative links to terms can be set, otherwise the default is used
* with enabled footer only the default terms are …
=> Add configuration to use footer with default terms

lib/Controller/PollApiController.php, lib/Controller/PollController.php, lib/Db/Poll.php, lib/Migration/TableSchema.php, lib/Migration/Version080000Date20250413195001.php, lib/Service/PollService.php, src/stores/poll.ts
Introduces voting variants for polls
* yes/no/may will be used as `simple` variant
* polls get a new attribute `votingVariant`
Voting variants may have a huge impact on configuration combinations. So this is why the base is introduced in 8.0.0 to allow further development.
addressing:
#3897
#3472
#3306
#1694
#1094
#765
#670
=> Prepare future voting variants

lib/Db/Preferences.php, src/App.vue, src/components/Base/index.ts, src/components/Base/modules/Collapsible.vue, src/components/Base/modules/HeaderBar.vue, src/components/Poll/MarkUpDescription.vue, src/components/Settings/UserSettings/StyleSettings.vue, src/stores/preferences.ts, src/views/Vote.vue
Long descriptions can take too much space. 
Collapses long descriptions (> 20 words or 5 lines) on opening the poll, if the participant has already voted. 
If the user did not vote until then, the description will be expanded on entering the poll and is collapsible.
=> Make description collapsible

lib/Db/Poll.php, lib/Model/UserBase.php, src/components/Actions/modules/ActionAddOption.vue, src/components/Base/modules/Collapsible.vue, src/components/Configuration/ConfigDescription.vue, src/components/Poll/MarkDownDescription.vue, src/components/Shares/SharesList.vue, src/components/SideBar/SideBarTabConfiguration.vue, src/components/User/UserSearch.vue, src/stores/poll.ts, src/views/Vote.vue
* Fix button caption - add option
* Fix deleted participants had no name in public polls
* Change the appearance of collapsed descriptions and add collapse configuration
* Fix pretending that users are hidden, when list view is selected
* shortening some hints in poll configuration sidebar tab
=> Some minor fixes/changes

lib/Model/UserBase.php, src/Types/index.ts, src/components/Base/modules/DateBox.vue, src/components/Export/ExportPoll.vue, src/components/Options/OptionItemDateBox.vue, src/components/Options/OptionsDateAddDialog.vue
fixes #4032
Luxon uses different language codes. Nextcloud gives i.e. `en_GB`, but Luxon expects `en-GB`.
See https://moment.github.io/luxon/api-docs/index.html#datetimesetlocale
Luxon seems to rely on the Intl-Formatting. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
=> Use different formatted language code for luxon

lib/Db/UserMapper.php, lib/UserSession.php
=> catch missing user for system jobs

lib/Controller/PollController.php, lib/Service/PollService.php, src/Api/modules/polls.ts, src/components/Actions/modules/ActionEditGroup.vue, src/components/PollGroup/PollGroupEditDlg.vue, src/stores/polls.ts, src/views/PollList.vue
Add editing the poll group attributes
=> Edit poll groups

src/components/Cards/VoteInfoCards.vue, src/components/VoteTable/VoteTable.vue, src/views/Vote.vue
* make fixed vote header default
* add a variant with flex items (activate by user settings)
In the result only the table is scrollable.
Side effect is a narrow vote table on small screens and when a lot of info cards are used
with info cards | without info cards
-|-
=> variant of fixed vote table header

CHANGELOG.md, lib/Db/LogMapper.php, lib/Service/MailService.php
* fix selecton of unprocessed entries
* switch processed timestamp to ms to avoid further exceptions
* sleep 5 ms between processed markers to avoid same ms timestamp on fast machines
fixes #4165
=> Fix setting log entries to processed on sent notification

src/App.vue, src/components/Base/modules/HeaderBar.vue, src/components/Base/modules/IntersectionObserver.vue, src/components/Base/modules/StickyDiv.vue, src/components/VoteTable/VoteColumn.vue, src/components/VoteTable/VoteTable.vue, src/stores/poll.ts, src/stores/votes.ts, src/views/Vote.vue
Changes are mainly affecting the vote page
* better scrolling behavior on safari
* fixing some visual issues in list-view when scrolling
* center the list-view and set width to content (fit-content)
* refactor IntersectionObserver
* refactor StickyDiv
=> fixing minor and major visual issues

CHANGELOG.md, lib/Controller/PollApiController.php, lib/Controller/PollController.php, lib/Db/Poll.php, lib/Service/CommentService.php, lib/Service/DiffService.php, lib/Service/MailService.php, lib/Service/OptionService.php, lib/Service/PollGroupService.php, lib/Service/PollService.php, lib/Service/ShareService.php, lib/Service/SubscriptionService.php, lib/Service/VoteService.php, lib/Service/WatchService.php, src/Api/modules/polls.ts, src/components/Configuration/ConfigAnonymous.vue, src/stores/poll.ts
Every single configuration change causes a complete round trip by patching all stores based on the reported request return.
Changes:
* Do not reload full poll on config changes
* Backend additionally sends the diff of the poll attributes after changing
* Only patch the diff to the poll store
* Selective reloading of other stores depending on the changed values
Additionally refactored the permission requests
In very big polls there is still a lag between the user action and applying the changes. Further investigation will be done, to determine, if this can be eliminated, too.
=> Just patch diff to poll store

CHANGELOG.md, lib/Service/ShareService.php
Fix an issue, where logged in useres were prevented to access a poll with the public share, after the second usage.
Users will no more get a new share, if they already have access to a poll.
fixes #4178
=> Fix using public share on already accessible poll

lib/Model/CalendarEvent.php, src/Api/modules/calendar.ts, src/components/Calendar/CalendarInfo.vue, src/components/Calendar/CalendarPeek.vue
* do not use cancelToken for fetching events (relates #4171)
* do not show conflict for events marked as free or available (TRANSP:TRANSPARENT)
resolve #3589
=> Fix some calendar issues

lib/Controller/PublicController.php, src/stores/poll.ts
=> async store loads

CHANGELOG.md, lib/Db/Poll.php, src/components/Configuration/AutoReminderInformation.vue, src/components/Configuration/ConfigAutoReminder.vue, src/components/SideBar/SideBarTabComments.vue, src/components/SideBar/SideBarTabConfiguration.vue, src/components/VoteTable/VoteTable.vue
* moved the configuration
* made comments available to owner ad delegated admins if disabled
* added a hint, in case commenting is not available for other participants
(Warning info card background is rather light since NC32 beta1)
=> Move comments config to comment tab

src/components/User/UserItem.vue
| b | a |
|--------|--------|
|<img width="1917" height="500" alt="image" src="https://github.com/user-attachments/assets/c49dfc40-7d53-4051-bbdf-377c95317043" /> |<img width="1917" height="500" alt="image" src="https://github.com/user-attachments/assets/0786e343-0215-4c35-bba7-c16728ab2610" /> |
=> fix: show full username on hover

README.md, appinfo/info.xml
=> Buy me a coffee

lib/Controller/UserController.php, lib/Db/Preferences.php, lib/Service/CalendarService.php, lib/Service/PreferencesService.php, src/components/Settings/UserSettings/CalendarSettings.vue, src/stores/preferences.ts, src/stores/preferences.types.ts
fixes #4171
The calendar key is not unique can can be mixed up by own calendars and subscribed calendars
* migrate usage of calendar URI instead of key
* rename preferences array to `settings` for better differentiation from the `Preferences ` class (backend side)
=> Migrate calendar keys to URI for calendarcheck

CHANGELOG.md, lib/Db/Preferences.php
=> Return default settings in case of empty user settings

lib/Command/Db/Rebuild.php, lib/Db/Share.php, lib/Db/V4/TableManager.php, lib/Service/ShareService.php, src/components/Combo/ComboTable.vue, src/components/Options/OptionItemOwner.vue, src/components/Shares/ShareItem.vue, src/components/Shares/ShareItemAllUsers.vue, src/components/Shares/SharePublicAdd.vue, src/components/User/UserAvatar.types.ts, src/components/User/UserAvatar.vue, src/components/User/UserBubble.vue, src/components/User/UserItem.vue
* use user.displayName instead of label
* refactor userItem and wrap NcAvatar into UserAvatar
=> Migrate share label of public polls to displayName of integrated user item

CHANGELOG.md, src/components/Activity/ActivityItem.vue, src/components/Cards/CardAddProposals.vue, src/components/Comments/CommentItem.vue, src/components/Poll/PollInfoLine.vue, src/components/Poll/PollInformation.vue, src/components/PollList/PollItem.vue, src/stores/poll.ts, src/views/Reference.vue
=> Add absolute locale dateTime as tooltip to relative dateTimes
