nextcloud/polls

- README.md
> added more info to the readme

- db/accessmapper.php
- db/commentmapper.php
- db/datemapper.php
- db/eventmapper.php
- db/notificationmapper.php
- db/participationmapper.php
- db/textmapper.php
Fixes #3
@Liwindo please review
> fix missing parameter in findEntity methods

- js/vote.js
> Fix typo in toggle-all

- templates/goto.tmpl.php
> remove double '>'

- controller/pagecontroller.php
> check for empty expire timestamp

- controller/pagecontroller.php
- js/vote.js
> fix pollid typo in controller

- templates/create.tmpl.php
> correctly show texts on edit

- appinfo/application.php
- controller/pagecontroller.php
- db/participationtext.php
- db/participationtextmapper.php
- templates/goto.tmpl.php
> Fix text votes

- templates/create.tmpl.php
Loads the description, if set. Fixes #26
> fix textarea creation

- js/vote.js
fixes #36, @danielepercivaldi please review.
> avoid negative total values

- controller/pagecontroller.php
fixes #34, what do you think @dekuenstle ?
> redirect to login before error page

- controller/pagecontroller.php
fixes #35, please review again @danielepercivaldi
> fix null pointer

- appinfo/application.php
- controller/pagecontroller.php
- db/commentmapper.php
- db/participationmapper.php
- db/participationtextmapper.php
- templates/goto.tmpl.php
fix #49 @darootler could you please test this PR?
> fixed some oc function errors

- controller/pagecontroller.php
fix #53 
@darootler and @nozof please review.
> use user's timezone for datetimes

- css/vote.css
This is a temporary fix. Please merge ASAP to make dates polls usable again.
> Fix header color

- css/vote.css
- templates/goto.tmpl.php
> Hotfix description newline

- templates/goto.tmpl.php
resolves https://github.com/v1r0x/polls/issues/56
> Proper Link for Polls

- templates/goto.tmpl.php
fix #63 
@EyesO could you please confirm if this works for you?
> add missing check for poll type

- css/create.css
- js/create_edit.js
- l10n/de.json
- l10n/de.php
- l10n/de_DE.json
- l10n/en.json
- l10n/en.php
- templates/create.tmpl.php
This should solve the issues #67, it least it works quit fine for me. Just try it out and merge it if you are happy with it. 
Cheers,
bodo
> changes in user and group pick list

- js/vote.js
@jaeger-sb proposed a change, in my environment it looks good, so I took the freedom to create this PR.
All Kudos to jaeger-sb!
> see issue #71 / handle different entry types

- appinfo/info.xml
> bump max oc version

- js/create_edit.js
fix #47 please review @danielepercivaldi
> make current selected access type clickable

- appinfo/database.xml
- controller/pagecontroller.php
- db/event.php
- db/eventmapper.php
- js/create_edit.js
- templates/create.tmpl.php
- templates/goto.tmpl.php
fix #38 please review @danielepercivaldi
Please note: You have to manually set the `<version>` in `appinfo/info.xml` to something higher than 0.7.1 (e.g. 0.7.1.1 for testing), since I had to update the database scheme.
> allow anonymous polls

- controller/pagecontroller.php
- js/vote.js
- templates/goto.tmpl.php
fix #62 please review @quizilkend
> allow anonymous comments

- templates/goto.tmpl.php
> make comments anonymous

- js/create_edit.js
fixes #70 please review @Mannshoch
> fix preselection on edit poll

- css/create.css
> visualize remove possibility

- appinfo/info.xml
> bump version

- appinfo/application.php
- controller/pagecontroller.php
- templates/create.tmpl.php
> remove unused share manager

- controller/pagecontroller.php
fix #101 
@scroom does this fix the problem for you?
> don't fetch hidden polls

- appinfo/database.xml
- appinfo/info.xml
- controller/pagecontroller.php
- db/event.php
- db/eventmapper.php
- js/create_edit.js
- templates/create.tmpl.php
- templates/goto.tmpl.php
Fix #100 Had to create a new branch/pull request. This is an updated version of #106 
Please review @scroom
> add extended anon type

- appinfo/database.xml
- appinfo/info.xml
- controller/pagecontroller.php
- db/event.php
- db/eventmapper.php
- js/create_edit.js
- templates/create.tmpl.php
- templates/goto.tmpl.php
fix #100 
@scroom what do you think about it? Only problem I see is that users could vote several times since the name is replaced by a random id
> add extended anon type, replace username with random id

- controller/pagecontroller.php
- templates/create.tmpl.php
- templates/goto.tmpl.php
Fixes issue #118 tested on Nextcloud 11.0.2 with php7. Please test on owncloud/earlier nextcloud releases for compatibility
> Changed type sensitive comparison for getType() to type-insensitive

- controller/pagecontroller.php
- js/create_edit.js
- js/vote.js
- templates/goto.tmpl.php
Fix #97 
The timezones should now be in UTC in the database and the user's (browser's) timezone offset is added to the dates.
Please review @poVoq and @uyekt
> Fix timezones

- appinfo/application.php
- appinfo/info.xml
- controller/pagecontroller.php
- db/accessmapper.php
- db/commentmapper.php
- db/datemapper.php
- db/eventmapper.php
- db/notificationmapper.php
- db/participationmapper.php
- db/participationtextmapper.php
- db/textmapper.php
- templates/main.tmpl.php
Fix #122 
I set up a NC 12 instance and had another error in my `nextcloud.log` file. My error was related to deprecated methods which have been removed in OC 10/NC 12. Does this still fix your error @joergmschulz ?
> replace deprecated methods

- appinfo/info.xml
found this app finally in the NC app-store. thank you!
but it looks a little bit sparse there, so i polished the description and added links... hopefully this is ok.
> polished app-info

- appinfo/info.xml
Polls works in NC 13 as expected
> Add NC 13 as max-version

- templates/create.tmpl.php
- templates/goto.tmpl.php
Adding NC default classes to checkboxed, radiobuttons and buttons.
> UI optimations

- templates/main.tmpl.php
> Fix for #86

- README.md
just a little update and cleanup "like discussed" in https://github.com/nextcloud/polls/pull/129#issuecomment-315737807
> brought the readme up to date

- css/vote.scss
- templates/create.tmpl.php
- templates/goto.tmpl.php
- templates/main.tmpl.php
- templates/navigation.tmpl.php
Hi @dartcafe 
Thanks for your PR #151 - I just had a look at it and don't want to push directly there. So I created a PR against your branch. Feel free to merge it into your "New design" PR by merging this PR here.
It removes the navigation bar on the left, fixes the home icon in the bread crumbs, increases the padding of the heading and removes the border as well as the padding around the "new comment" in the public poll page.
Before:
After:
> New design polishing

- .gitignore
- CHANGELOG.md
- LICENSE
- README.md
- appinfo/database.xml
- appinfo/info.xml
I tried to match Decks and other NC apps README. I am looking forward to dig deeper into NC developement and help to refactor the source code 💪
Would be nice if you could also change the repo description to sth. like:
> Update README + add license

- lib/Controller/PageController.php
Fix #192 
Please review @hajika and @dartcafe
> update anonymous state as well on poll update

- css/createpoll.css
> added forgotten createpoll.css

- .travis.yml
- Makefile
@v1r0x could you test this? It generates the signature.json via occ and signs the .tar.gz package. It also compiles the scss files for the oC release.
> Added package signing + scss compilation to Makefile

- appinfo/info.xml
OC is a pile of sh*t....They have wrong info in their dev manual and useless restrictions...Anyway:
Polls is released on the oc marketplace (which is horrible as well...) using the changes in this branch. The `Makefile` works very well :) (if run with `sudo -u www-data` 😅 ) Thanks @splitt3r 
Could someone please approve these changes @splitt3r @dartcafe ? :)
> update info.xml structure for oc marketplace

- css/list.scss
cc @nextcloud/designers 
http://caniuse.com/#search=flex
> Vendor prefix for flexbox not needed anymore

- lib/Controller/PageController.php
> Fix Server Error for non-existing poll

- Makefile
- lib/AppInfo/Application.php
- lib/Controller/PageController.php
- tests/Unit/Factories/CommentFactory.php
- tests/Unit/Factories/EventFactory.php
- tests/Unit/Factories/ParticipationTextFactory.php
- tests/Unit/Factories/TextFactory.php
As mentioned in https://github.com/nextcloud/appstore/pull/530#issuecomment-340269827 we should remove the occ signing before we release a version containing the signature.json @v1r0x
> Remove occ signing

- js/vote.js
Fix for non accessible avatars in public polls, when using owncloud.
> fix-oc-avatars

- templates/goto.tmpl.php
@dartcafe requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/nextcloud/polls/
> Scrutinizer Auto-Fixes

- CHANGELOG.md
- js/vote.js
- src/js/Create.vue
- #348 - Open Sidebar in vote page by default (when screen-size <1024px)
- Change adminMode to computed
> Open sidebar by default

- lib/Controller/ApiController.php
fixes #431
Load options html decoded
trim options on save
> Load options html decoded

- appinfo/info.xml
- css/vote.scss
> fix poll width

- appinfo/info.xml
- lib/Migration/Version0009Date20181125051900.php
- lib/Migration/Version0009Date20181125061900.php
#453 - Polls upgrade leads to NotNullConstraintViolationException
#454 - Update to 0.9.3 failed for postgresql database
> Migration fix 2

- src/js/components/pollListItem.vue
- src/js/components/shareDiv.vue
- src/js/main.js
- src/js/plugins/modalDialog.vue
- src/js/views/Create.vue
- src/js/views/List.vue
Allow shifting of all date options in one step.
> Shift all dates of a date poll with given step and unit

- src/js/components/pollListHeader.vue
- src/js/components/pollListItem.vue
- src/js/views/Create.vue
- src/js/views/List.vue
display access with icon instead of text #497
> display access with icon instead of text #497

- lib/Controller/ApiController.php
#511 access permission was not properly checked
> #511 - added missing access check

- lib/Controller/ApiController.php
- src/js/views/Create.vue
#461 - Polls with expire date could not be created/edited
> fix expire date could not be created/edited (#461)

- src/js/components/pollListItem.vue
> resize type icons (#516)

- css/vote.scss
> #528 Change overflow-x of table element

- CHANGELOG.md
- README.md
- appinfo/info.xml
- package.json
> Repckaging for #532

- appinfo/info.xml
- package.json
- src/js/main.js
> Updated version and dependencies

- templates/vote.tmpl.php
Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#lt_LT/polls/129942219
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>
> Fixed typo

- src/js/components/VoteTable/VoteHeaderPublic.vue
- src/js/views/PollList.vue
> l10n. Fixed grammar

- appinfo/info.xml
- appinfo/routes.php
- lib/Controller/EventController.php
- lib/Controller/NoticeController.php
- lib/Controller/OptionController.php
- lib/Controller/ShareController.php
- lib/Controller/SubscriptionController.php
- lib/Controller/VoteController.php
- lib/Cron/NotificationCron.php
- lib/Db/EventMapper.php
- lib/Db/Log.php
- lib/Db/LogMapper.php
- lib/Db/Notice.php
- lib/Db/NoticeMapper.php
- lib/Db/ShareMapper.php
- lib/Db/Subscription.php
- lib/Db/SubscriptionMapper.php
- lib/Migration/Version0010Date20191221183157.php
- lib/Model/Acl.php
- lib/Service/LogService.php
- lib/Service/MailService.php
- src/js/components/Subscription/Subscription.vue
- src/js/store/index.js
- src/js/store/modules/subscription.js
- src/js/views/PublicVote.vue
- src/js/views/Vote.vue
- tests/Unit/Controller/PageControllerTest.php
- tests/Unit/Db/SubscriptionMapperTest.php
- tests/Unit/Factories/SubscriptionFactory.php
Bring back notification on poll updates
> Notification

- appinfo/routes.php
- lib/Controller/OptionController.php
- lib/Controller/PollController.php
- lib/Controller/ShareController.php
- lib/Model/Acl.php
- src/js/components/VoteTable/VoteHeaderPublic.vue
- src/js/store/modules/acl.js
- src/js/store/modules/poll.js
- src/js/store/modules/shares.js
- src/js/views/PublicVote.vue
> fix public votes

- lib/Controller/CommentController.php
- lib/Controller/SystemController.php
- lib/Service/MailService.php
- src/js/components/Comments/CommentAdd.vue
- src/js/views/PollList.vue
> Fix comments

- lib/Controller/SystemController.php
- lib/Service/MailService.php
> Fix shares #726

- src/js/components/Base/PollInformation.vue
> Change grammar.

- src/js/components/Base/PollInformation.vue
> Fixed grammar, added dot

- src/js/components/Comments/Comments.vue
- src/js/components/PollList/PollListItem.vue
- src/js/store/modules/comments.js
- src/js/views/PollList.vue
* changing popovermenu to Actions (#594 and #754 )
* updated design according to file lists
* Sorting polls in poll list, default creation date desc (#559 and #717)
> Sort polls in poll list

- lib/Controller/ShareController.php
- lib/Service/MailService.php
Creating personal share with individual user name threw errors on some systems.
> Fix creating personal share #771

- appinfo/routes.php
- lib/Controller/PageController.php
> routing optimizations

- lib/Model/Acl.php
- src/js/store/modules/acl.js
- src/js/views/PublicVote.vue
> Allow site user to vote in hidden poll via public link #779

- lib/Controller/CommentController.php
- lib/Controller/SystemController.php
- lib/Db/Comment.php
- lib/Db/Poll.php
- lib/Db/Share.php
- lib/Db/Vote.php
- lib/Model/Acl.php
- lib/Service/MailService.php
- src/js/components/Base/ParticipantsList.vue
- src/js/components/Base/UserDiv.vue
- src/js/components/Comments/CommentAdd.vue
- src/js/components/Comments/Comments.vue
- src/js/components/SideBar/SideBarTabShare.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/store/modules/votes.js
Show displayName instead of userId #715
> Add display names

- src/js/components/SideBar/SideBarTabConfiguration.vue
> workaround for #830

- lib/Controller/PollController.php
- lib/Db/Poll.php
- lib/Model/Acl.php
- src/js/components/Base/PollDescription.vue
- src/js/components/PollList/PollListItem.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/store/modules/poll.js
> Empty description

- lib/Controller/PollController.php
- lib/Db/Poll.php
- lib/Model/Acl.php
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/store/modules/poll.js
> fixes setting admin rights, disable fullAnonymous

- src/js/components/Navigation/Navigation.vue
Pin deleted polls on the bottom of the navigation tree
> Pinned navigationItem "Deleted polls"

- src/js/App.vue
- src/js/components/VoteTable/VoteHeaderPublic.vue
fix text color change in dark mode, when using darkreader add-on (https://github.com/darkreader/darkreader)
> workaround darkReader (browser add-on)

- src/js/components/VoteTable/VoteTableItem.vue
> fix #841 - changed vote icons

- src/js/components/Base/ButtonDiv.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/SideBar/SideBarTabOptionsDate.vue
- src/js/components/SideBar/SideBarTabShare.vue
- src/js/components/VoteTable/VoteHeaderPublic.vue
- src/js/views/Vote.vue
- added icons to buttons
- removed primary class
- switched headerButtons to ActionButtons (switch and sidebar)
Before
After
Before
After
Before
After
- fixed buttons overlapping title (#847)
> Button style

- src/js/components/VoteTable/VoteHeaderPublic.vue
> l10n: Fixed grammar

- lib/Service/MailService.php
> Keep the user anonymous #871

- lib/Controller/PollController.php
- src/js/App.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/PollList/PollListItem.vue
- src/js/components/Subscription/Subscription.vue
- src/js/views/PollList.vue
- src/js/views/Vote.vue
closes #864
- replaced duplicated code
- autoreload poll list
> Avoid double loading of poll list

- lib/Controller/OptionController.php
- lib/Db/Option.php
order in date polls was not properly set under some circumstances 
fix #861
> force options order by timestamp in date polls

- CHANGELOG.md
- appinfo/info.xml
- lib/Migration/Version0104Date20200314074611.php
- package.json
Preparation for version update
> Version 1.4.0

- src/js/views/PollList.vue
- src/js/views/Vote.vue
> set window title

- lib/Controller/VoteController.php
- lib/Db/VoteMapper.php
- lib/Model/Acl.php
- src/js/components/Base/PollInformation.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/PollList/PollListItem.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/components/VoteTable/VoteTableHeader.vue
- src/js/views/Vote.vue
> [1.4.0 beta1] Safari bugs

- lib/Service/MailService.php
> Add poll description to invitation mail

- src/js/components/Base/PollInformation.vue
Signed-off-by: Valdnet <valdnet@itvix.pl>
> Adding a space character

- CHANGELOG.md
- lib/Controller/ShareController.php
- lib/Controller/SystemController.php
- lib/Controller/VoteController.php
- src/js/components/Base/ButtonDiv.vue
- src/js/components/VoteTable/VoteHeaderPublic.vue
fix #909 and #910 
* added / fixed backend checks
* fix :disabled 
* prevent using forbidden username with enter
> Fix public user

- src/js/components/Base/OptionAddDate.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
fix #957 
* changed datetimepicker's minute step to 5 minutes for date poll options and expiry date
> raise minute step to 5 min dor datetimepicker

- src/js/components/VoteTable/VoteHeaderPublic.vue
> Change prompt for name in public polls

- src/js/components/Base/OptionAddDate.vue
> Don't add empty date option

- lib/Service/MailService.php
> skip disabled users

- lib/Service/MailService.php
> Hide usernames if results are hidden

- package-lock.json
- package.json
- src/js/components/Navigation/Navigation.vue
Update to nextcloud/vue 2.2
use navigation slot
> Nextcloud vue 2

- appinfo/routes.php
- lib/Controller/PollApiController.php
- lib/Controller/PollController.php
- lib/Db/ShareMapper.php
- lib/Db/Vote.php
- lib/Service/MailService.php
- lib/Service/PollService.php
- src/js/components/Base/ParticipantsList.vue
- src/js/store/modules/poll.js
Owner may collect  email addresses from participants for further usage. 
Fix #978
> Collect email addresses

- appinfo/routes.php
- lib/Controller/PollController.php
- lib/Controller/ShareController.php
- lib/Controller/SubscriptionController.php
- lib/Exceptions/InvalidShareType.php
- lib/Model/Acl.php
- lib/Service/CommentService.php
- lib/Service/MailService.php
- lib/Service/OptionService.php
- lib/Service/PollService.php
- lib/Service/ShareService.php
- lib/Service/SubscriptionService.php
- lib/Service/VoteService.php
- src/js/App.vue
- src/js/components/Base/PersonalLink.vue
- src/js/components/Base/PublicRegisterModal.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/SideBar/SideBarTabShare.vue
- src/js/components/Subscription/Subscription.vue
- src/js/components/VoteTable/VoteHeaderPublic.vue
- src/js/store/modules/poll.js
- src/js/store/modules/subModules/share.js
- src/js/store/modules/subModules/shares.js
- src/js/store/modules/subscription.js
- src/js/views/Vote.vue
Give public users the option 
* to add email address
* subscribe to updates
* send personal link to their email address
fixes #853 
fixes #286
> Public subscription

- appinfo/routes.php
- lib/Controller/OptionController.php
- lib/Service/OptionService.php
- src/js/components/Base/OptionCloneDate.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/store/modules/subModules/options.js
fixes #1058 - moving creation of object sequence to backend
> move option sequence to backend 

- appinfo/routes.php
- lib/Controller/PreferencesController.php
- lib/Db/Preferences.php
- lib/Db/PreferencesMapper.php
- lib/Migration/Version0105Date20200523142076.php
- src/js/App.vue
- src/js/components/Base/Counter.vue
- src/js/components/Calendar/CalendarInfo.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/Navigation/NavigationSettings.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/store/modules/settings.js
Adding settings menu for
* deactivating calendar peek
* some experimental layout options
> Background experimental

- .gitignore
- lib/Db/Poll.php
- lib/Migration/Version0105Date20200903172733.php
- lib/Service/PollService.php
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/store/modules/poll.js
- src/js/store/modules/polls.js
> Adding option for important polls

- package.json
- src/js/views/Vote.vue
Added linkify for URIs in description.
fixes #1067
> use linkifyjs for description

- src/js/components/VoteTable/VoteTableHeaderItem.vue
> fix counter in mobile view

- appinfo/routes.php
- lib/Controller/CommentController.php
- src/js/store/modules/subModules/comments.js
> [fix] delete comments in public polls

- src/js/components/Base/OptionShiftDates.vue
> fix date shifting

- CHANGELOG.md
- appinfo/info.xml
- package.json
Bugfix release 1.5.5
@v1r0x Are you able to add another release. The Bugfixes are already in the master.
We could ship the review tagged PR as well to get them from the desk.
Could be good to wait the with the release 3 days after merging the PRs to get a chance for translations.
> Version 1.5.5

- src/js/App.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/Settings/ExpertimantalSettings.vue
- src/js/components/Settings/FeatureSettings.vue
- src/js/components/Settings/SettingsDlg.vue
> Move settings to new AppSettingsDialog from nextcloud-vue

- lib/Service/MailService.php
> fix wrong link for external users in notification mail

- lib/Controller/ShareApiController.php
- lib/Controller/ShareController.php
- lib/Db/Share.php
- lib/Migration/Version0106Date20201031080745.php
- lib/Migration/Version0106Date20201031080946.php
- lib/Model/Acl.php
- lib/Model/Contact.php
- lib/Model/UserGroupClass.php
- lib/Service/MailService.php
- lib/Service/ShareService.php
- src/js/components/Base/PersonalLink.vue
- src/js/components/Base/PublicRegisterModal.vue
- src/js/components/Base/UserItem.vue
- src/js/components/SideBar/SideBarTabShare.vue
- src/js/components/Subscription/Subscription.vue
- src/js/store/modules/subModules/share.js
- src/js/store/modules/subModules/shares.js
> Fix public vote

- appinfo/routes.php
- lib/Controller/PublicController.php
- lib/Service/MailService.php
- lib/Service/ShareService.php
- src/js/components/Base/PersonalLink.vue
- src/js/components/Base/PublicRegisterModal.vue
- src/js/store/modules/subModules/share.js
- src/js/store/modules/subModules/shares.js
* Fix after the last refactoring
Registration and resending invitation was broken.
> fixing registration and resending invitation mail

- appinfo/routes.php
- lib/Controller/SystemController.php
- lib/Model/UserGroupClass.php
- lib/Service/SystemService.php
- src/js/components/SideBar/SideBarTabShare.vue
> Cancel concurrent request on share searching

- lib/Model/Circle.php
- lib/Model/Contact.php
- lib/Model/ContactGroup.php
- lib/Model/Email.php
- lib/Model/Group.php
- lib/Model/User.php
- lib/Model/UserGroupClass.php
- lib/Service/ShareService.php
- lib/Service/SystemService.php
- src/js/components/Base/PublicRegisterModal.vue
fix #881 - Switched from the individual searches to ISearch for circles, users and groups.
> fix #881 - respect autocompletion restrictions from share settings

- appinfo/routes.php
- lib/Controller/AdminController.php
- lib/Controller/PollController.php
- lib/Db/Log.php
- lib/Db/PollMapper.php
- lib/Model/Acl.php
- lib/Notification/Notifier.php
- lib/Service/CommentService.php
- lib/Service/MailService.php
- lib/Service/NotificationService.php
- lib/Service/OptionService.php
- lib/Service/PollService.php
- lib/Service/ShareService.php
- lib/Service/SubscriptionService.php
- lib/Service/VoteService.php
- src/js/App.vue
- src/js/components/Base/Badge.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/PollList/PollItem.vue
- src/js/components/PollList/PollItemAdmin.vue
- src/js/router.js
- src/js/store/modules/pollsAdmin.js
- src/js/views/Administration.vue
- src/js/views/PollList.vue
- src/js/views/Vote.vue
Introducing an admin section for admin users
* fix #924 Admin get the possibilty to see a list (and only a list) of polls, from other users
functions so far:
> Adding admin section

- src/js/views/Vote.vue
* pull poll updates every 30 seconds (fix #907)
> timed poll updates

- src/js/components/Base/PollInformation.vue
> Improve plural handling

- lib/Db/VoteMapper.php
- lib/Model/Acl.php
- lib/Service/VoteService.php
- src/js/components/VoteTable/VoteTableVoteItem.vue
- src/js/store/modules/subModules/votes.js
* Moved limits check from Acl to voteService
* Only count votes corresponding to an actual existing option
> Make sure only valid votes are counted

- lib/Model/Acl.php
prevent commenting, when entering public poll without registration
> disallow commenting with public shares

- CHANGELOG.md
- lib/Model/UserGroupClass.php
> Fix usersearch

- lib/Db/Log.php
- lib/Db/LogMapper.php
- lib/Migration/Version0107Date20201210160301.php
- lib/Migration/Version0107Date20201210204702.php
- lib/Migration/Version0107Date20201210213303.php
- lib/Migration/Version0107Date20201217071304.php
- lib/Migration/Version0107Date20210101161105.php
- lib/Migration/Version0107Date20210121220707.php
- lib/Service/LogService.php
- lib/Service/MailService.php
- tests/Unit/Factories/LogFactory.php
fix #1355
- removed column message
- fixed index creation
> fix migration

- CHANGELOG.md
- appinfo/info.xml
- appinfo/routes.php
- lib/Controller/ResponseHandle.php
- lib/Controller/WatchController.php
- lib/Db/Watch.php
- lib/Db/WatchMapper.php
- lib/Exceptions/NoUpdatesException.php
- lib/Migration/Version0108Date20210127135802.php
- lib/Service/CommentService.php
- lib/Service/OptionService.php
- lib/Service/PollService.php
- lib/Service/VoteService.php
- lib/Service/WatchService.php
- package.json
- src/js/App.vue
- src/js/components/Settings/ExpertimantalSettings.vue
- src/js/store/modules/poll.js
- src/js/store/modules/settings.js
- src/js/store/modules/subModules/comments.js
- src/js/store/modules/subModules/votes.js
- src/js/views/Vote.vue
Watch changes and apply immediately, instead of timed object polling.
> Watch events

- src/js/components/Options/OptionsDateShift.vue
Fix shifting of dates, when a shifted date hits an already existing option.
> fix uniqueConstraint error

- lib/Service/PreferencesService.php
hotfix #1388 
Giving preferences a default value to avoid possible DB problems. 
Needs further investigation
> Default value for preferences #1388

- lib/Db/Option.php
- src/js/assets/icons/minus.svg
- src/js/assets/scss/icons.scss
- src/js/components/Base/ButtonDiv.vue
- src/js/components/Base/CheckBoxDiv.vue
- src/js/components/Base/InputDiv.vue
- src/js/components/Base/RadioGroupDiv.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Settings/ExpertimantalSettings.vue
- src/js/components/Settings/FeatureSettings.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/Subscription/Subscription.vue
* RadioGroup
* Checkbox
* Numeric mode for InputDiv
* Simple submit button
> Some custom controls components for simplification of code

- src/js/assets/scss/hacks.scss
- src/js/components/Base/PublicRegisterModal.vue
fixes #1400
fixes #1401
fixes #1418
> Registration Dlg fixes and optimizations

- appinfo/routes.php
- lib/Controller/PublicController.php
- lib/Controller/ShareController.php
- lib/Service/ShareService.php
- src/js/App.vue
- src/js/assets/scss/colors-dark.scss
- src/js/assets/scss/colors.scss
- src/js/components/Base/InputDiv.vue
- src/js/components/Base/PublicEmail.vue
- src/js/components/Base/PublicRegisterModal.vue
- src/js/components/Comments/CommentAdd.vue
- src/js/components/Options/OptionsTextAdd.vue
- src/js/components/VoteTable/VoteItem.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/store/modules/share.js
- src/js/views/Vote.vue
> Let public users change their email address

- lib/Model/Contact.php
- lib/Model/ContactGroup.php
- lib/Model/Group.php
- lib/Model/User.php
Search to contactgroups was broken
> fixed contactgroups in usersearch

- lib/Notification/Notifier.php
fix #1421 - Remove notification, if poll not found
> remove notification, if poll not found #1421

- lib/Service/MailService.php
> fix comparism in mail controller

- appinfo/routes.php
- lib/Controller/OptionController.php
- lib/Service/OptionService.php
- src/js/components/Options/OptionsDateShift.vue
- src/js/store/modules/options.js
By shifting dates a uniqueContraint validation can be raised. 
Moving shifting dates away from frontend to backend
> move shift date to backend

- src/js/components/Poll/MarkUpDescription.vue
Don't display html content of the description property.
> don't display html tags in description

- src/js/App.vue
- src/js/components/Navigation/Navigation.vue
- src/js/components/Poll/PollInformation.vue
- src/js/components/Settings/FeatureSettings.vue
- src/js/components/VoteTable/VoteItem.vue
- src/js/mixins/watchPolls.js
- src/js/store/modules/poll.js
- src/js/store/modules/polls.js
- src/js/store/modules/votes.js
- src/js/views/PollList.vue
Replaces some code elements for better readability.
> Misc code optimizations

- src/js/helpers/detectColorScheme.js
> fix detectColorScheme

- src/js/assets/scss/hacks.scss
- src/js/components/Calendar/CalendarInfo.vue
- src/js/components/Calendar/CalendarPeek.vue
- src/js/components/VoteTable/VoteTable.vue
* adjust dark mode colors in calendarPeek 
* scroll bar needs some distance from the vote table on some devices (currently, it is inside the vote table)
* make sidebar tabs scrollable, instead of sidebar or whole page
> Some minor design fixes

- src/js/components/Configuration/ConfigAccess.vue
- src/js/components/Configuration/ConfigAdminAccess.vue
- src/js/components/Configuration/ConfigAllowComment.vue
- src/js/components/Configuration/ConfigAllowMayBe.vue
- src/js/components/Configuration/ConfigAnonymous.vue
- src/js/components/Configuration/ConfigClosing.vue
- src/js/components/Configuration/ConfigDescription.vue
- src/js/components/Configuration/ConfigOptionLimit.vue
- src/js/components/Configuration/ConfigShowResults.vue
- src/js/components/Configuration/ConfigTitle.vue
- src/js/components/Configuration/ConfigVoteLimit.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
The SideBarTabConfiguration Component got rather huge. So relieve it and split configuration in components
> Split configuration in components

- lib/Helper/Trace.php
- lib/Service/SystemService.php
> username as search parameter

- src/js/components/VoteTable/VoteItem.vue
- src/js/store/modules/votes.js
Fix #1519
Added a toast notification with a 2 second timeout after a vote click.
> Add toast notification after vote

- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/SideBar/SideBarTabOptions.vue
adding new options was not possible, if a poll has no options
> fix add options in new poll

- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Poll/PublicRegisterModal.vue
> l10n: Correct and add a word

- src/js/components/Poll/PublicRegisterModal.vue
> l10n: Revert change

- appinfo/info.xml
- lib/Cron/JanitorCron.php
- lib/Cron/NotificationCron.php
- lib/Db/LogMapper.php
- lib/Db/WatchMapper.php
Add a daily job to remove 
* processed entries and entries older than 7 days oc_polls_log and
* entries older than one day from oc_watch
> Add a janitor job to tidy log and watch tables from old entries

- src/js/components/Actions/ActionDelete.vue
- src/js/components/Comments/CommentItem.vue
- src/js/components/Options/OptionItemOwner.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Shares/SharesEffective.vue
- src/js/components/Shares/SharesPublic.vue
- src/js/components/Shares/SharesUnsent.vue
- src/js/components/VoteTable/VoteTable.vue
Enhance deletion of votes, option like deletion of comments
- Use a 7 second timeout before deletion is executed
- let the user abort the deletion
> Add delete action component with undelete

- lib/Controller/PreferencesController.php
- lib/Service/PreferencesService.php
- src/js/components/Settings/ExpertimantalSettings.vue
> fix settings

- lib/Db/Poll.php
- lib/Db/VoteMapper.php
- lib/Migration/Version0200Date20210323120002.php
- lib/Service/VoteService.php
- src/js/components/Configuration/ConfigUseNo.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/store/modules/poll.js
Added option to display a 'no' vote as unvoted option, due to expected irritation of participants.
Actually the vote gets deleted according to what's displayed.
> Option to handle no as unvoted

- lib/Db/Option.php
- lib/Migration/Version0109Date20210323120002.php
> option owner "disallow"

- lib/Service/MailService.php
- src/js/components/Shares/SharesEffective.vue
- src/js/components/Shares/SharesUnsent.vue
> Add displayname to Invitation notice

- src/js/components/Configuration/ConfigProposals.vue
- src/js/components/Options/OptionsDateAdd.vue
> fix firstDayOfWeek #1560

- src/js/components/Configuration/ConfigClosing.vue
- src/js/components/Configuration/ConfigProposals.vue
- src/js/components/PollList/PollItem.vue
- src/js/components/PollList/PollItemAdmin.vue
- src/js/components/VoteTable/VoteTable.vue
Explicit define closing date meaning and fix typo
Accidentially added fix for vote table header alignment
> closing date

- appinfo/routes.php
- src/js/store/modules/comments.js
- src/js/store/modules/options.js
- src/js/store/modules/poll.js
- src/js/store/modules/polls.js
- src/js/store/modules/pollsAdmin.js
- src/js/store/modules/settings.js
- src/js/store/modules/share.js
- src/js/store/modules/shares.js
- src/js/store/modules/subscription.js
- src/js/store/modules/votes.js
> add unique parameter to axios.get

- CHANGELOG.md
- appinfo/info.xml
- package.json
- src/js/assets/scss/print.scss
Fixing a print issue, when printing in list layout
> fix printing layout

- docs/API_v1.0.md
- lib/Controller/OptionApiController.php
fix  #1689 
Additional delivery for #1365
> add option duration to API

- lib/Model/Group.php
- lib/Model/User.php
- lib/Model/UserGroupClass.php
> Do not send mails to disabled group members

- src/js/components/Options/OptionItem.vue
> display day of optionItem without ordinal suffix/prefix

- lib/Event/CommentEvent.php
- lib/Event/OptionEvent.php
- lib/Event/VoteEvent.php
fix some actors in events for public polls
> fix actor in events

- src/js/store/modules/polls.js
Reported by the translator at Transifex.
> l10n: Correct a typo

- appinfo/info.xml
- lib/Db/Option.php
- lib/Db/OptionMapper.php
- lib/Db/VoteMapper.php
- lib/Migration/FixVotes.php
- src/js/components/Options/OptionItem.vue
> Migrate votes to new representation, if option has a duration

- lib/Migration/FixVotes.php
Avoid running fixVotes on first time install
> fix migration for first time run

- appinfo/info.xml
- lib/Db/Option.php
- lib/Db/OptionMapper.php
- lib/Db/VoteMapper.php
- lib/Migration/DeleteInvalidRecords.php
- lib/Migration/FixVotes.php
- lib/Migration/Version030000Date20210611120000.php
- src/js/components/Options/OptionItem.vue
> apply changes from #1762 for #1749 manually

- src/js/App.vue
- src/js/components/Options/OptionProposals.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Poll/PollTitle.vue
- src/js/components/SideBar/SideBar.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/views/Administration.vue
- src/js/views/PollList.vue
- src/js/views/Vote.vue
Load components asynchronously
> lazy component loading

- lib/Migration/TableSchema.php
fixes #1788 
* change all field lengths for userIds and displayNames to 256
> Adjusting field lengths

- appinfo/info.xml
- lib/Controller/PublicController.php
- lib/Controller/SubscriptionApiController.php
- lib/Controller/SubscriptionController.php
- lib/Event/PollDeletedEvent.php
- lib/Migration/CreateIndices.php
- lib/Migration/RemoveIndices.php
- lib/Migration/TableSchema.php
- lib/Migration/Version030000Date20210704120000.php
- lib/Model/Group.php
- lib/Notification/Notifier.php
- lib/Service/SubscriptionService.php
- package.json
- src/js/components/Actions/ActionDelete.vue
- src/js/components/Calendar/CalendarPeek.vue
- src/js/components/VoteTable/VoteColumn.vue
- src/js/components/VoteTable/VoteTable.vue
fixes #1808 
fixes #1807 
fixes #1806
> Version/3.0.0 rc.2

- lib/Migration/FixVotes.php
> fix compatibily trap between NC20 and NC21 #1811

- composer.json
- composer.lock
- lib/Db/LogMapper.php
- lib/Db/OptionMapper.php
- lib/Db/PreferencesMapper.php
- lib/Db/ShareMapper.php
- lib/Db/SubscriptionMapper.php
- lib/Db/VoteMapper.php
- lib/Service/LogService.php
- lib/Service/OptionService.php
- lib/Service/SubscriptionService.php
DBAL Exceptions must remain for NC21
marked as depricated NC22
fix #1815
> NC21 compatibility - keep DBAL Exceptions

- lib/Db/LogMapper.php
- lib/Db/OptionMapper.php
- lib/Db/PreferencesMapper.php
- lib/Db/ShareMapper.php
- lib/Db/SubscriptionMapper.php
- lib/Db/VoteMapper.php
- lib/Migration/TableSchema.php
- lib/Migration/Version030000Date20210704120000.php
- lib/Notification/Notifier.php
adding return types and let psalm do some magic
> type hints, annotations and camel case

- src/js/components/Poll/PollHeaderButtons.vue
- src/js/components/Poll/PollInformation.vue
- src/js/components/SideBar/SideBarTabUserOptions.vue
- src/js/components/User/UserItem.vue
- src/js/components/User/UserMenu.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/views/Navigation.vue
- src/js/views/SideBar.vue
- src/js/views/Vote.vue
Adopting proposal from #1602
Standard layout (before): 
Condensed layout (first iteration):
> use condensed userItem for participants

- lib/Controller/PublicController.php
- lib/Db/Option.php
- lib/Db/Poll.php
- lib/Service/AnonymizeService.php
replace userIds with displayname in public polls
> obfuscate userIds in public polls

- composer.json
> move Doctrine/DBAL to dev-dependencies

- src/js/components/User/UserItem.vue
> Set user-item to max-width: 100%

- src/js/components/Poll/PollTitle.vue
> remove translation without translatable text

- lib/Db/Share.php
- lib/Model/AppSettings.php
- lib/Service/SettingsService.php
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/Settings/AdminMisc.vue
- src/js/store/modules/appSettings.js
> Configure login option for public polls in admin panel

- src/js/components/Settings/AdminPollCreation.vue
- src/js/components/Settings/AdminShareSettings.vue
> l10n: Correct text string

- src/js/views/AdminSettingsPage.vue
In my opinion, the change introduces a more professional solution.
> l10n:Change word

- lib/Db/Poll.php
- lib/Migration/TableSchema.php
- lib/Service/ShareService.php
- src/js/components/Configuration/ConfigProposals.vue
- src/js/components/Configuration/ConfigPublicPollsEmail.vue
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/Shares/SharesPublic.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/mixins/writePoll.js
- src/js/store/modules/poll.js
resolves #1728 
Define per poll:
* optional email address 
* mandatory email address
* disable email address
resulting in
> configure mail address for public polls

- lib/Service/SystemService.php
- src/js/components/Poll/PublicRegisterModal.vue
> Remove 3 character rule for public usernames

- appinfo/routes.php
- lib/Controller/PublicController.php
- lib/Controller/VoteController.php
- lib/Event/VoteEvent.php
- lib/Service/VoteService.php
- src/js/components/User/UserMenu.vue
- src/js/store/modules/votes.js
resolves  #1578
Add a menu item to let the user delete his own votes
> allow users to reset their votes

- src/js/components/User/UserMenu.vue
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> Changed grammar

- appinfo/routes.php
- lib/Controller/ShareController.php
- lib/Db/Share.php
- lib/Model/Acl.php
- lib/Model/Admin.php
- lib/Model/User.php
- lib/Model/UserGroupClass.php
- lib/Service/ShareService.php
- src/js/components/Shares/SharesEffective.vue
- src/js/components/User/UserItem.vue
- src/js/store/modules/shares.js
solves #1095 
Grant poll admin access for invited users (only internal users)
> grant poll admin rights to invitee

- lib/Model/AppSettings.php
- lib/Service/AnonymizeService.php
- lib/Service/PreferencesService.php
- lib/Service/SettingsService.php
* hardening AppConfig against missing or misconfigured values
* adding type hints
> refactor and type hints

- lib/Model/Acl.php
> allow delegated admins to see result and user names

- .eslintrc.js
- src/js/components/Base/RadioGroupDiv.vue
- src/js/components/Options/OptionItem.vue
- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Poll/PublicEmail.vue
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/Settings/AdminPollCreation.vue
- src/js/components/Settings/AdminShareSettings.vue
- src/js/components/User/UserItem.vue
- src/js/components/User/UserMenu.vue
- src/js/components/User/UserSearch.vue
- src/js/mixins/watchPolls.js
- src/js/store/modules/comments.js
- src/js/store/modules/options.js
- src/js/store/modules/poll.js
- src/js/store/modules/pollsAdmin.js
- src/js/store/modules/share.js
- src/js/store/modules/shares.js
- src/js/store/modules/subscription.js
- src/js/store/modules/votes.js
- src/js/views/Administration.vue
- src/js/views/PollList.vue
- src/js/views/Vote.vue
set eslint prefer-template and update code to use template literals over string concentation
> use template literals instead of string concentation

- src/js/App.vue
- src/js/components/Actions/ActionChangeView.vue
- src/js/components/Actions/ActionToggleSidebar.vue
- src/js/components/Poll/PollHeaderButtons.vue
- src/js/components/Settings/SettingsDlg.vue
- src/js/views/Administration.vue
- src/js/views/Navigation.vue
- src/js/views/PollList.vue
- src/js/views/SideBar.vue
- src/js/views/Vote.vue
https://github.com/nextcloud/nextcloud-event-bus#naming-convention
> rename events according to documentation (@nextcloud/event-bus)

- src/js/components/Shares/SharesEffective.vue
- src/js/components/Shares/SharesUnsent.vue
- src/js/components/User/UserItem.vue
resolves #1943
Add email address (if any) to the share entry. Only for external and mail/contact shares
User after registered via email invitation and entered username
> Show email address in sharelist for external and mail shares

- appinfo/info.xml
> l10n: Change name to a capital letter

- lib/Service/OptionService.php
> fix sort by rank

- lib/Service/ShareService.php
- src/js/components/Poll/PublicRegisterModal.vue
> Duplicate check status message

- src/js/components/Configuration/AutoReminderInformation.vue
> Fix wording in autoreminder explanation

- CHANGELOG.md
- lib/Model/Mail/InvitationMail.php
> Add groupname to invitation

- CHANGELOG.md
- appinfo/info.xml
- lib/Db/Option.php
- package.json
> Fix error on adding poll option

- lib/Db/Share.php
- lib/Service/ShareService.php
- src/js/components/Poll/PublicRegisterModal.vue
> fix email constraints for public poll registrations

- lib/Db/Option.php
- lib/Service/AnonymizeService.php
- lib/Service/OptionService.php
> anonymize proposal owner in anonymous polls

- lib/Model/Acl.php
> Don't allow adding proposal with public share

- lib/Service/ActivityService.php
follow up to #2155
* Changing tense to present perfect
* correction of actors
> Tense and corrections in activities

- lib/Service/ActivityService.php
Signed-off-by: rakekniven <2069590+rakekniven@users.noreply.github.com>
> l10n: Fixed grammar and changed wording of genitive case

- src/js/components/Export/ExportPoll.vue
- src/js/store/modules/votes.js
> l10n: Change to uppercase

- lib/Notification/Notifier.php
> skip and remove notification on exception

- CHANGELOG.md
- package-lock.json
- package.json
- src/js/components/Options/OptionItem.vue
> linkify options

- lib/Migration/TableSchema.php
regarding migration gap between very old versions (prior 2.x) and the current 
fix #2201 
fix #2199
> migration fixes

- lib/Model/UserGroup/Circle.php
- lib/Model/UserGroup/Contact.php
- lib/Model/UserGroup/ContactGroup.php
- lib/Model/UserGroup/Email.php
- lib/Model/UserGroup/GenericUser.php
- lib/Model/UserGroup/Group.php
- lib/Model/UserGroup/User.php
- lib/Model/UserGroup/UserBase.php
> changed class loading and change error level to warning

- lib/Model/UserGroup/Contact.php
- lib/Model/UserGroup/User.php
change display of user search results and add the email address to found users and contacts.
resolve #2264
> return email address in user search for users and contacts resolve #2264

- CHANGELOG.md
- src/js/components/Export/ExportPoll.vue
> fix export

- lib/Exceptions/OCPEventException.php
- lib/Listener/BaseListener.php
- lib/Listener/GroupDeletedListener.php
- lib/Listener/UserDeletedListener.php
> invalid function call in listener when deleting users from nextcloud

- src/js/components/Export/ExportPoll.vue
> limit sheet name length

- package-lock.json
- package.json
- templates/admin.php
- templates/polls.tmpl.php
- templates/settings.php
- webpack.config.js
Update webpack config and dependencies
> use @nextcloud/webpack-vue-config

- src/js/components/Base/ConfigBox.vue
Add slot for material design icons to configBox
> Support material design icons with configbox

- src/js/components/Options/OptionsDate.vue
- src/js/views/Administration.vue
@nextcloud/vue aftermath
Change modal text
> fix modal heights

- lib/Model/UserGroup/UserBase.php
fix #1310 
Added ISearch::TYPE_EMAIL to search types for better search results (i.e. in LDAP environments)
> Add ISearch::TYPE_EMAIL to user search

- lib/Controller/PublicController.php
- lib/Service/SystemService.php
> Fix Exception upon validation of usernames and email addresses

- src/js/components/PollList/PollItem.vue
- src/js/views/Administration.vue
> remove poll route on admin page

- src/js/views/Administration.vue
> l10n: Correct typo

- appinfo/routes.php
- lib/Controller/OptionController.php
- lib/Service/OptionService.php
- src/js/App.vue
- src/js/components/Base/ConfigBox.vue
- src/js/components/Options/OptionCloneDate.vue
- src/js/components/Options/OptionsTextAddBulk.vue
- src/js/components/SideBar/SideBarTabOptions.vue
- src/js/store/modules/options.js
Allow to import a list of text options at once
```
Option one
2
tree
vier
```
creates four new text options.
> Add bulk import for text polls

- appinfo/routes.php
- lib/Controller/OptionController.php
- lib/Service/OptionService.php
- src/js/App.vue
- src/js/components/Base/ConfigBox.vue
- src/js/components/Options/OptionCloneDate.vue
- src/js/components/Options/OptionProposals.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Options/OptionsTextAddBulk.vue
- src/js/components/SideBar/SideBarTabOptions.vue
- src/js/store/modules/options.js
* move the button to section header
* add material design icon
* remove button text when in options sidebar
> Change AddDate button

- .gitignore
- jsconfig.json
- package-lock.json
- package.json
Add prettier and plugins for switching to Visual Studio Code
**possibly necessary to more to add later**
> add prettier for vetur and vscode

- src/js/components/Options/OptionsDateAdd.vue
Fix #2313 - Changed method of string selection
The original way seems to find no way to transifex
> Change selection method #2313

- src/js/assets/scss/icons-md.scss
> Fix icon display in chrome

- src/js/components/Base/RadioGroupDiv.vue
- src/js/components/Combo/ComboTable.vue
- src/js/components/Options/OptionItem.vue
- src/js/components/User/UserItem.vue
- src/js/components/VoteTable/VoteTable.vue
> Refactoring

- src/js/components/Export/ExportPoll.vue
- src/js/store/modules/poll.js
Fix #2407 - Export fails, if downloader (=owner) did not vote in current poll
> Fix poll export, if downloader did not vote

- src/js/components/Settings/UserSettings/CalendarSettings.vue
- src/js/views/Navigation.vue
1. Proposed changes of sentences by a translator from Transifex.
2. Changing the l10n directory.
> l10n: Reconstruction of sentences and change l10n

- src/js/components/SideBar/SideBarTabOptions.vue
> Fix click button on adding date option

- lib/Db/VoteMapper.php
- src/js/components/Export/ExportPoll.vue
* Fix export of polls with characters, which are not allowed for the sheet name
* Fix collecting of email address 
fixes #2433
> strip illegal characters from sheet name

- lib/Service/SystemService.php
* skips invalid username and email address results
fixes #2440
> fix empty array result on user search

- src/js/components/Poll/PublicRegisterModal.vue
> l10n: Add word "Name"

- src/js/App.vue
- src/js/components/Base/InputDiv.vue
- src/js/components/Comments/CommentAdd.vue
- src/js/components/Configuration/ConfigOptionLimit.vue
- src/js/components/Configuration/ConfigTitle.vue
- src/js/components/Configuration/ConfigVoteLimit.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Options/OptionCloneDate.vue
- src/js/components/Options/OptionsDateShift.vue
- src/js/components/Options/OptionsTextAdd.vue
- src/js/components/Poll/PublicEmail.vue
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/Settings/AdminSettings/AdminCombo.vue
- src/js/components/Settings/AdminSettings/AdminEmail.vue
- src/js/components/Settings/AdminSettings/AdminHideMailAddresses.vue
- src/js/components/Settings/AdminSettings/AdminLegal.vue
- src/js/components/Settings/AdminSettings/AdminMisc.vue
- src/js/components/Settings/AdminSettings/AdminPerformance.vue
- src/js/components/Settings/AdminSettings/AdminPollCreation.vue
- src/js/components/Settings/AdminSettings/AdminPollDownload.vue
- src/js/components/Settings/AdminSettings/AdminShareSettings.vue
- src/js/components/Settings/UserSettings/CalendarSettings.vue
- src/js/components/Settings/UserSettings/FeatureSettings.vue
- src/js/components/Settings/UserSettings/PerformanceSettings.vue
- src/js/components/Settings/UserSettings/StyleSettings.vue
- src/js/views/AdminSettingsPage.vue
- src/js/views/UserSettingsPage.vue
* Refactoring of InputDiv
* Consistently use InputDiv
* Update props and design
* Reduce noise in modals using inputs
> Standardize InputDiv

- src/js/components/Poll/PublicRegisterModal.vue
> l10n: Add a dot

- src/js/components/Base/InputDiv.vue
See #2461 
regarding comment https://github.com/nextcloud/polls/issues/2461#issuecomment-1160838728
> [3.7.0-beta5] fix description width bug

- src/js/components/Poll/PublicRegisterModal.vue
> remove term username

- src/js/components/Poll/PublicRegisterModal.vue
- src/js/router.js
- src/js/store/modules/share.js
* only set cookie when registering via public share
* avoid endless redirects if cookie name is equal to cookie value
fix #2466
> fix endless redirects

- src/js/components/User/UserMenu.vue
- src/js/helpers/cookieHelper.js
- src/js/router.js
fixes #2359 
* adds a menu entry to the user menu to logout from the public poll
* Redirects to the public poll page after logout to allow registerinng of another public participant
> Allow logging out from a public poll, when cookie is set

- src/js/components/Comments/CommentItem.vue
> Linkify comments

- src/js/components/User/UserItem.vue
Fix avatar of public users to generate Avatar letters from displayname and not from generated username
> fix avatar of public users

- appinfo/routes.php
- lib/AppInfo/Application.php
- lib/Controller/PublicController.php
- lib/Event/ShareChangedDisplayNameEvent.php
- lib/Listener/ShareListener.php
- lib/Service/ActivityService.php
- lib/Service/ShareService.php
- src/js/components/User/UserMenu.vue
- src/js/store/modules/share.js
Allow users to change their name after registration to the public poll
fix #2400
> allow public users changing their name

- lib/Service/ActivityService.php
- src/js/components/User/UserMenu.vue
> l10n: Correct spelling

- lib/AppInfo/Application.php
- lib/Db/CommentMapper.php
- lib/Db/LogMapper.php
- lib/Db/OptionMapper.php
- lib/Db/PollMapper.php
- lib/Db/PreferencesMapper.php
- lib/Db/ShareMapper.php
- lib/Db/SubscriptionMapper.php
- lib/Db/VoteMapper.php
- lib/Db/WatchMapper.php
- lib/Helper/Container.php
- lib/Listener/BaseListener.php
- lib/Migration/DeleteInvalidRecords.php
- lib/Migration/TableSchema.php
- lib/Service/ActivityService.php
- lib/Service/CalendarService.php
- psalm-baseline.xml
* Eliminate private namespace OC, where possible
* update psalm baseline
* fix some annotations
* remove deprecated methods (supersedes #2470)
> Classes refactoring

- CHANGELOG.md
- src/js/components/Export/ExportPoll.vue
Skip export of missing participants (mainly the owner). 
fix #2522
> skip participant on error

- package-lock.json
- package.json
- src/js/App.vue
- src/js/components/Base/FlexSpacer.vue
- src/js/components/Calendar/CalendarPeek.vue
- src/js/components/Combo/ComboTable.vue
- src/js/components/Comments/Comments.vue
- src/js/components/Export/ExportPoll.vue
- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Poll/MarkUpDescription.vue
- src/js/components/Poll/PublicEmail.vue
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/User/UserMenu.vue
- src/js/components/User/UserSearch.vue
- src/js/components/VoteTable/VoteColumn.vue
- src/js/mixins/adminSettingsMixin.js
- src/js/mixins/writePoll.js
- src/js/store/modules/combo.js
- src/js/store/modules/index.js
- src/js/store/modules/options.js
- src/js/store/modules/polls.js
- src/js/views/Administration.vue
> manually update @nextcloud/eslint-config@8.1.2

- src/js/components/Actions/ActionSendConfirmedOptions.vue
> l10n: Change "mail" to "email"

- .github/workflows/static-analysis.yml
- lib/Db/Comment.php
- lib/Db/Log.php
- lib/Db/Option.php
- lib/Db/Poll.php
- lib/Db/Preferences.php
- lib/Db/Share.php
- lib/Db/Subscription.php
- lib/Db/Vote.php
- lib/Db/Watch.php
- lib/Model/Settings/AppSettings.php
* added return type for internal php classes (php 8.1)
fix #2565
> add types for internal PHP classes

- package-lock.json
- package.json
- src/js/components/Activity/ActivityItem.vue
- src/js/components/Poll/PublicRegisterModal.vue
switch to @nextcloud/vue-richtext@2
> implement @nextcloud/vue-richtext

- package-lock.json
- package.json
> use @nextcloud/initial-state

- src/js/views/SideBar.vue
from #2544
Signed-off-by: Christopher Ng <chrng8@gmail.com>
> Hide deprecated projects in sidebar by default

- src/js/Exceptions/Exceptions.js
- src/js/mixins/watchPolls.js
> change watchPolls

- lib/Controller/PublicController.php
- lib/Db/Comment.php
- lib/Db/Log.php
- lib/Db/Option.php
- lib/Db/Poll.php
- lib/Db/Preferences.php
- lib/Db/Share.php
- lib/Db/Subscription.php
- lib/Db/Vote.php
- lib/Db/Watch.php
- lib/Exceptions/InvalidPollIdException.php
- lib/Model/Acl.php
- lib/Model/Mail/NotificationMail.php
- lib/Model/Settings/AppSettings.php
- lib/Service/MailService.php
- lib/Service/PollService.php
- lib/Service/ShareService.php
- lib/Service/UserService.php
- lib/Service/VoteService.php
- src/js/components/Options/OptionsDate.vue
* remove some orphaned methods
* some maintenance
* surpress error logs with PHP 8.1 by changing return type of `jsonSerialize()` to `: array`
`Error: Return type of [...]::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice at [...]`
* fix permission on voting in public polls, whan comments are disabled (#2600)
> Code maintenance

- .github/workflows/static-analysis.yml
- composer.json
- composer.lock
See https://github.com/nextcloud/server/issues/32117#issuecomment-1259211942
> update christophwurst/nextcloud to nextcloud/ocp

- .github/workflows/phpunit.yml
- src/js/assets/scss/markdown.scss
- src/js/components/Options/OptionItem.vue
- src/js/components/Poll/MarkUpDescription.vue
- src/js/components/Poll/PollInfoLine.vue
- src/js/components/Poll/PublicRegisterModal.vue
replace deprecated css variables:
- `color-text-light` → `color-main-text`
- `color-text-lighter` → `color-text-maxcontrast`
Additionally:
set postges image to `14.5-bullseye` in test action
> replace deprecated css variables

- src/js/components/SideBar/SideBarTabComments.vue
> fix empty comments

- src/js/Api/appSettings.js
- src/js/Api/polls.js
- src/js/Api/userSettings.js
- src/js/mixins/watchPolls.js
- src/js/store/modules/pollsAdmin.js
* app settings
* take over poll
* user settings
> Api fixes after more testing

- lib/Controller/ShareController.php
- lib/Db/Log.php
- lib/Db/Option.php
- lib/Db/Poll.php
- lib/Db/Share.php
- lib/Db/ShareMapper.php
- lib/Db/Subscription.php
- lib/Db/Vote.php
- lib/Db/Watch.php
- lib/Event/ShareEvent.php
- lib/Event/VoteSetEvent.php
- lib/Helper/Container.php
- lib/Listener/BaseListener.php
- lib/Middleware/RequestAttributesMiddleware.php
- lib/Model/Mail/MailBase.php
- lib/Model/Mail/NotificationMail.php
- lib/Model/UserBase.php
- lib/Provider/ActivityProvider.php
- lib/Service/ActivityService.php
- lib/Service/CalendarService.php
- lib/Service/NotificationService.php
- lib/Service/PreferencesService.php
- lib/Service/ShareService.php
- src/js/Api/calendar.js
- src/js/Api/public.js
* remove deprecations
* kill some psalm warnings
> remove some deprecations

- lib/Controller/PublicController.php
> remove footer from public pages due to overlapping

- lib/Db/Option.php
> Allow nullish option owner

- lib/Db/Option.php
> [stable-3] Allow nullish option owner

- lib/Service/VoteService.php
> fix "Reset your votes" throws error #2683

- src/js/views/Dashboard.vue
> scoped and optimized dashboard css

- src/js/App.vue
- src/js/components/Base/InputDiv.vue
- src/js/components/Poll/PublicRegisterModal.vue
> Change registration dialog

- src/js/store/modules/options.js
> fix option confirmation

- src/js/assets/scss/print.scss
- src/js/components/Options/Counter.vue
- src/js/components/VoteTable/VoteTable.vue
|  | before | after |
| - | - | - |
| light | ![grafik](https://user-images.githubusercontent.com/26707476/208040708-0832ee30-601d-472a-a02f-fa572ba87045.png) | ![grafik](https://user-images.githubusercontent.com/26707476/208039181-78a6d2c5-cf69-4590-88d7-4be997de4912.png) |
| dark | ![grafik](https://user-images.githubusercontent.com/26707476/208040753-1ecbe238-3a59-4896-b0c4-f92de04ba2df.png) | ![grafik](https://user-images.githubusercontent.com/26707476/208039535-674f62bf-4b5f-4772-a2c6-4e30691b9c56.png) |
> Update vote page design according to NC design refresh

- src/js/Api/calendar.js
- src/js/components/Calendar/CalendarPeek.vue
- src/js/store/modules/options.js
- src/js/store/modules/pollsAdmin.js
- src/js/store/modules/share.js
> misc fixes

- CHANGELOG.md
- lib/Migration/TableSchema.php
- lib/Migration/Version041000Date20221221070000.php
> allow 1024 char in options texts

- img/polls.svg
> add color to icon

- lib/Settings/AdminSection.php
- lib/Settings/PersonalSection.php
Fixing colors of icons in settiongs sections
> fix settings icon color

- appinfo/info.xml
- lib/Command/Db/AddIndices.php
- lib/Command/Db/Rebuild.php
- lib/Command/Db/RemoveIndices.php
- lib/Migration/CreateIndices.php
- lib/Migration/RemoveIndices.php
- lib/Migration/TableSchema.php
- lib/Migration/Version041000Date20221221070000.php
- psalm-baseline.xml
Some refactoring and optizations of 
- migration and
- occ commands regarding database rebuild
> migration and command optimizations

- CHANGELOG.md
- appinfo/info.xml
- lib/Migration/TableSchema.php
- lib/Migration/Version040101Date20230119080000.php
- package-lock.json
- package.json
> fix-invitations

- .github/workflows/phpunit.yml
- CHANGELOG.md
- appinfo/info.xml
- lib/Db/Poll.php
- lib/Migration/TableSchema.php
- lib/Migration/Version040102Date20230123072601.php
- package-lock.json
- package.json
* Use another approach in the code to avoid nullish descriptions and title 
The migration has some flaws, the db structure does not migrate properly
> fix invitations attempt 2

- .github/workflows/phpunit.yml
- CHANGELOG.md
- appinfo/info.xml
- lib/Command/Db/Rebuild.php
- lib/Db/Option.php
- lib/Db/OptionMapper.php
- lib/Db/TableManager.php
- lib/Db/Vote.php
- lib/Db/VoteMapper.php
- lib/Migration/RepairSteps/UpdateHashes.php
- lib/Migration/TableSchema.php
- package-lock.json
- package.json
fixes #2758 
* updated the database to set the unique index to a generated hash instead of the long option text. The hash compresses the 
* injected a hash generation into the update and insert methods
* added repair step
* added hash update to rebuild command
* switched from mariaDB to MySQL in checks
> Change indexing strategy for votes and options

- CHANGELOG.md
- appinfo/info.xml
- lib/Migration/TableSchema.php
- package-lock.json
- package.json
- src/js/components/Options/OptionsDateAdd.vue
* Fix disappeared option add button after change in the nextcloud-vue lib
* Changed option owner column to notnull
> Apply some fixes

- lib/Command/Share/Add.php
- lib/Model/Acl.php
- lib/Model/Settings/AppSettings.php
- lib/Notification/Notifier.php
- lib/Service/ActivityService.php
- lib/Service/ShareService.php
- lib/Service/UserService.php
Take advantage of `match` statement over `switch`
> Replace switch with match

- CHANGELOG.md
- appinfo/info.xml
- lib/Db/Poll.php
- lib/Migration/TableSchema.php
- package-lock.json
- package.json
fixes #2792
* allow `null` for column `description` and set default to null
> Fix/stable 4/description default

- lib/Db/Preferences.php
- lib/Service/PreferencesService.php
Adding a default set to the user preferences to avoid nullish preferences
fix  #2819
> add default to user preferences

- CHANGELOG.md
- lib/Service/ShareService.php
- src/js/components/Base/QrModal.vue
- src/js/components/Shares/SharesList.vue
* Shorten token for public polls to 8 characters
* remove button from qr modal
> Shorten token for public shares

- lib/Exceptions/ForbiddenException.php
- lib/Model/Acl.php
- lib/Service/OptionService.php
- lib/Service/PollService.php
- lib/Service/ShareService.php
Replace NoAuthorized with Fobidden status code
> appropiate http status forbidden

- lib/Service/VoteService.php
fix reset own votes for non admin users
> fix reset own votes

- CHANGELOG.md
- appinfo/info.xml
- lib/Model/UserBase.php
> nullable email address

- lib/Db/Log.php
- lib/Model/Mail/NotificationMail.php
> fix notifications

- CHANGELOG.md
- src/js/Api/options.js
> fix bulk adding of options

- appinfo/info.xml
> Add Nextcloud 27 support

- lib/Db/Preferences.php
- src/js/components/Settings/UserSettings/StyleSettings.vue
- src/js/components/VoteTable/VoteColumn.vue
- src/js/components/VoteTable/VoteItem.vue
- src/js/store/modules/settings.js
- src/js/views/Vote.vue
* Added changed style as beta option 
* activate via Styles in user settings (Polls Settings)
resolves #2908
> Change vote page design (beta setting)

- src/js/dashboard.js
No need to use full store for the dashboard widget
> don't use full store for dashboard widget

- appinfo/info.xml
- lib/Command/Db/Rebuild.php
- lib/Db/TableManager.php
- lib/Migration/RepairSteps/UpdateInteraction.php
> change repair step order

- lib/Model/User/Email.php
- lib/Model/User/GenericUser.php
- lib/Service/UserService.php
> fix export with nullish email addresses

- package-lock.json
- package.json
- src/js/components/Actions/ActionChangeView.vue
- src/js/components/Actions/ActionDelete.vue
- src/js/components/Actions/ActionSendConfirmedOptions.vue
- src/js/components/Actions/ActionSortOptions.vue
- src/js/components/Actions/ActionToggleSidebar.vue
- src/js/components/Configuration/ConfigClosing.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Navigation/PollNavigationItems.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Options/OptionsDateShift.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Options/OptionsTextAddBulk.vue
- src/js/components/Poll/MarkUpDescription.vue
- src/js/components/Poll/PollHeaderButtons.vue
- src/js/components/Settings/AdminSettings/AdminEmail.vue
- src/js/components/VoteTable/VoteColumn.vue
- src/js/views/Navigation.vue
* migrated NcAppNavigationItem from deprecated `title` to `name`
* removed marked deprecations
* added missing aria lebels to NcButton
> Remove deprecations and other warnings

- src/js/assets/scss/colors.scss
- src/js/components/Base/InputDiv.vue
- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/User/UserMenu.vue
* removed paddings for modals
* Removed status background colors from edit fields
> some minor design changes

- lib/Db/TableManager.php
Hey,
@unteem caught a typo you made in https://github.com/nextcloud/polls/pull/2950 which cause all rows de be deleted.
> fix(deleteDuplicates): select only duplicates

- lib/Service/UserService.php
* Avoid exception on unparsable user search items and 
* add debug logging for these items
fixes #2944
> workaround and debug logging

- package-lock.json
- package.json
* replaces #2951 
* Update xlsx (away from npm to common install)
* misc version updates
> Dep Updates

- src/js/components/Calendar/CalendarPeek.vue
- src/js/components/VoteTable/VoteColumn.vue
> fix calendar peek for conflict detection

- CHANGELOG.md
- lib/Service/SubscriptionService.php
> Fix subscriptions

- src/js/components/Poll/PublicRegisterModal.vue
- src/js/components/Shares/SharesList.vue
> text changes

- src/js/components/Shares/SharesList.vue
- src/js/components/User/UserItem.vue
> replace individual icons

- lib/Command/Command.php
- lib/Command/Db/CleanMigrations.php
- lib/Command/Db/CreateIndices.php
- lib/Command/Db/Purge.php
- lib/Command/Db/Rebuild.php
- lib/Command/Db/RemoveIndices.php
- lib/Command/Db/ResetWatch.php
- lib/Db/IndexManager.php
- lib/Db/TableManager.php
- lib/Migration/FixVotes.php
- lib/Migration/RepairSteps/CreateIndices.php
- lib/Migration/RepairSteps/CreateTables.php
- lib/Migration/RepairSteps/DeleteInvalidRecords.php
- lib/Migration/RepairSteps/DropOrphanedColumns.php
- lib/Migration/RepairSteps/DropOrphanedTables.php
- lib/Migration/RepairSteps/Install.php
- lib/Migration/RepairSteps/RemoveIndices.php
- lib/Migration/RepairSteps/RemoveObsoleteMigrations.php
- lib/Migration/RepairSteps/UpdateHashes.php
- lib/Migration/RepairSteps/UpdateInteraction.php
- lib/Migration/Version050100Date20230515083001.php
* Change construction of commands
* Change migration to return ISchemaWrapper
fixes #2980
fixes #3010
> Refactor database operations for commands, repair steps and migrations

- lib/Provider/ActivityProvider.php
- lib/Service/ActivityService.php
> fix activity

- CHANGELOG.md
- appinfo/info.xml
Getting it out after a lot of smoke testing
> Release 5.3.0

- lib/Service/ShareService.php
> Fix creating public shares

- src/js/components/Shares/ShareItem.vue
> fix granting admin rights

- src/js/components/Base/index.js
- src/js/components/Base/modules/FlexSettings.vue
- src/js/views/AdminSettingsPage.vue
- src/js/views/UserSettingsPage.vue
Moved flex layout of settings pages into its own component
> move template for settings into base component

- src/js/assets/scss/colors.scss
* fix dark colors in public polls
> Fixes for 5.4.0-beta-4

- appinfo/info.xml
- src/js/components/Options/OptionsText.vue
- src/js/views/Vote.vue
Fixing aftermath of latest changes
* render error when closing text polls
* add missing getter mapping
> fix some bugs after testing

- src/js/components/Shares/ShareItem.vue
Changed some terms to avoid possible misunderstanding for translations
> Change terms for clarification in translations

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/nodejs.yml
- .github/workflows/phpunit.yml
- .github/workflows/static-analysis.yml
* only Nextcloud 28 and up
* update to @nextcloud/vue@8
* change properties as needed in @nextcloud/vue@8
> Support Nextcloud 28 and @nextcloud/vue@8

- src/js/components/Actions/modules/ActionSendConfirmed.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/views/Vote.vue
* Use info status instead of succes for some cards
* enhance feedback on sending confirmation mails
> Use info type for some cards

- package-lock.json
- package.json
> update to nextcloud-vue beta10

- src/js/components/Actions/modules/ActionDelete.vue
- src/js/components/Actions/modules/ActionSendConfirmed.vue
- src/js/components/Base/modules/ConfigBox.vue
- src/js/components/Base/modules/QrModal.vue
- src/js/components/Comments/CommentItem.vue
- src/js/components/Configuration/ConfigTitle.vue
- src/js/components/Create/CreateDlg.vue
- src/js/components/Options/OptionItemOwner.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Settings/UserSettingsDlg.vue
- src/js/components/Shares/ShareItem.vue
- src/js/components/Shares/SharesList.vue
- src/js/components/Shares/SharesListLocked.vue
- src/js/components/Shares/SharesListUnsent.vue
- src/js/components/SideBar/SideBarTabActivity.vue
- src/js/components/SideBar/SideBarTabComments.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/SideBar/SideBarTabOptions.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/views/AdminSettingsPage.vue
- src/js/views/Administration.vue
- src/js/views/Combo.vue
- src/js/views/NotFound.vue
- src/js/views/PollList.vue
- src/js/views/SideBarCombo.vue
- src/js/views/UserSettingsPage.vue
- src/js/views/Vote.vue
* change prop title to required prop name for nectcloud-vue components
* consistently use prop name in own components
> change prop title to name

- tests/Integration/Command/Share/TShareCommandTest.php
- tests/Unit/Controller/PageControllerTest.php
- tests/Unit/Db/CommentMapperTest.php
- tests/Unit/Db/LogMapperTest.php
- tests/Unit/Db/OptionMapperTest.php
- tests/Unit/Db/PollMapperTest.php
- tests/Unit/Db/SubscriptionMapperTest.php
- tests/Unit/Db/VoteMapperTest.php
- tests/Unit/Factories/PreferencesFactory.php
- tests/Unit/UnitTestCase.php
just some tidy
* remove typehints from annotations to typed properties
> use typed properies

- package-lock.json
- package.json
- update-app-version.mjs
Write version to `appinfo/info.xml` on executing `npm version`.
* use npm version script
* gets version as generated or named with `npm version`
* add appinfo/info.xml to version commit
> synchronize app version with npm version

- src/js/components/Actions/modules/ActionChangeView.vue
- src/js/components/Actions/modules/ActionDelete.vue
- src/js/components/Actions/modules/ActionSendConfirmed.vue
- src/js/components/Actions/modules/ActionSortOptions.vue
- src/js/components/Actions/modules/ActionToggleSidebar.vue
- src/js/components/Base/modules/ConfigBox.vue
- src/js/components/Combo/ComboTable.vue
- src/js/components/Combo/VoteColumn.vue
- src/js/components/Options/OptionItem.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsDateAdd.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Poll/PollHeaderButtons.vue
- src/js/components/Poll/PublicEmail.vue
- src/js/components/PollList/PollItem.vue
- src/js/components/Shares/SharesListUnsent.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/VoteTable/VoteColumn.vue
- src/js/views/SideBar.vue
* Following https://github.com/nextcloud-libraries/nextcloud-vue/issues/2503
* Migrated some icons
> change v-tooltip to native tooltip

- lib/Model/Acl.php
- lib/Service/ShareService.php
* fixes session information after personal registration to poll
> fix public registering

- appinfo/info.xml
- lib/Db/EntityWithUser.php
- lib/Db/VoteMapper.php
- lib/Event/BaseEvent.php
- lib/Model/Acl.php
- lib/Service/PollService.php
- lib/Service/VoteService.php
- package-lock.json
- package.json
- src/js/components/Shares/ShareItem.vue
- src/js/components/User/UserItem.vue
- src/js/components/VoteTable/VoteTable.vue
* fix wrong user type
* add type icon to share avatars and allow user avatars from initials even for external users
* better identification of deleted users
> fixing some weird user apperance

- lib/Db/PollMapper.php
- src/js/components/Base/modules/HeaderBar.vue
> fix search column #3203

- package-lock.json
- package.json
- src/js/components/Poll/MarkUpDescription.vue
- src/js/components/Settings/AdminSettings/AdminEmail.vue
> remove marked-mangle #3201

- lib/Model/Search/PollsSearchResultEntry.php
- lib/Model/User/Ghost.php
- lib/Model/UserBase.php
* fixed classes parent to UserBase
> Deleted user has wrong parent class

- appinfo/info.xml
- lib/Filter/ActivityFilter.php
- lib/Model/UserBase.php
- lib/Provider/ActivityProvider.php
- lib/Service/ActivityService.php
- src/js/Api/modules/activity.js
- src/js/components/Activity/ActivityItem.vue
There are still some issues, regarding the activity app
> Minor activities fixes

- lib/Db/Preferences.php
> fix preferences

- CHANGELOG.md
- src/js/assets/scss/transitions.scss
- src/js/components/Activity/Activities.vue
- src/js/components/Combo/ComboTable.vue
- src/js/components/Comments/Comments.vue
- src/js/components/Options/OptionItem.vue
- src/js/components/Options/OptionsDate.vue
- src/js/components/Options/OptionsText.vue
- src/js/components/Shares/ShareItem.vue
- src/js/components/Shares/SharesList.vue
- src/js/components/Shares/SharesListLocked.vue
- src/js/components/Shares/SharesListUnsent.vue
- src/js/components/SideBar/SideBarTabOptions.vue
- src/js/components/User/UserMenu.vue
- src/js/components/VoteTable/VoteTable.vue
- src/js/store/modules/shares.js
- src/js/views/Administration.vue
- src/js/views/PollList.vue
Dependent on #3246
* Move all action items to actions button
* clamp options in sidebar to 2 lines
* expand clamped option on fover or active state
* fixes #2878
> sidebar enhancements -options and shares lists

- lib/Controller/PublicController.php
- lib/Exceptions/NoEmailAddress.php
- lib/Service/MailService.php
- lib/Service/ShareService.php
- lib/Service/SystemService.php
* add better email string parser for extracting Names and email addresses
* Move mail parsing to MailService
> parse email and move to MailService

- lib/Service/CalendarService.php
Skip processing calendar event, if no valid objects are contained.
> capture invalid calendar event

- appinfo/info.xml
> create hashes before deleting invalid entries

- lib/Model/Acl.php
> fix DELETE: Option owner or poll id missing

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/PublicController.php
- lib/Controller/ShareController.php
- lib/Exceptions/ShareAlreadyExistsException.php
- lib/Service/ShareService.php
- lib/Service/SystemService.php
- src/js/Api/modules/public.js
> Fix reaccessing poll as internal user with public link

- CHANGELOG.md
- src/js/Api/modules/validators.js
> fix username check

- CHANGELOG.md
- src/js/components/User/UserSearch.vue
> fix NcSelect

- lib/Service/SystemService.php
> strip some unicodes from public username

- lib/Db/OptionMapper.php
- lib/Db/Poll.php
- lib/Db/PollMapper.php
- psalm-baseline.xml
regarding #3362
alternative approach to #3363
> join timestamps from options

- lib/AppInfo/Application.php
- lib/Controller/PollController.php
- lib/Cron/JanitorCron.php
- lib/Db/Share.php
- lib/Helper/Container.php
- lib/Model/Acl.php
- lib/Model/Settings/AppSettings.php
- lib/Model/UserBase.php
- lib/Service/SettingsService.php
- lib/Service/WatchService.php
- tests/Unit/Db/CommentMapperTest.php
- tests/Unit/Db/LogMapperTest.php
- tests/Unit/Db/OptionMapperTest.php
- tests/Unit/Db/PollMapperTest.php
- tests/Unit/Db/SubscriptionMapperTest.php
- tests/Unit/Db/VoteMapperTest.php
* Register some Classes via `OCP\AppFramework\Bootstrap\IRegistrationContext::registerService`
* Load classes via `OCP\Server::get()` in some cases, where depenency injection is not possible (i.e. static methods)
> Register Services

- CHANGELOG.md
- lib/Service/OptionService.php
> fix nullish poll id for public users on date suggestion

- lib/AppConstants.php
- lib/Controller/BasePublicController.php
- lib/Controller/PublicController.php
- lib/Db/Poll.php
- lib/Middleware/RequestAttributesMiddleware.php
- lib/Service/CommentService.php
> Bring back registration on public polls

- src/js/App.vue
> bring back the combo-view

- CHANGELOG.md
- appinfo/routes.php
- lib/Controller/PollApiController.php
Added an endpoint to the REST Api to fetch the acl of a poll
resolves #3414
> adding an acl endpoint to the api controller

- CHANGELOG.md
- lib/Service/CommentService.php
- lib/Service/OptionService.php
- lib/Service/SubscriptionService.php
- lib/Service/VoteService.php
> catch error on requesting votes of non existing poll

- src/js/store/modules/polls.js
- src/js/views/PollList.vue
Manual backport of https://github.com/nextcloud/polls/pull/3444
> [stable6] fix: Add visual loading feedback for polls list

- src/js/router.js
> Revert "Default to "My polls" view"

- src/js/assets/scss/transitions.scss
- src/js/components/Base/modules/BadgeDiv.vue
- src/js/components/Poll/PollInformation.vue
- src/js/components/PollList/PollItem.vue
- src/js/views/Administration.vue
- src/js/views/Navigation.vue
- src/js/views/PollList.vue
* Tidy for the flexbox usage
* Show table header while loading
* Reduced transition time upon poll list changes
> refactoring of polls list with leaner flexbox

- .eslintrc.js
- .prettierignore
- .prettierrc.json
- package-lock.json
- package.json
change config to support prettier
> change ESLint config to work with prettier

- src/js/mixins/adminSettingsMixin.js
> Aftermath: Fixing type error

- lib/Db/PollMapper.php
> do not send autoreminders for archived polls

- .github/workflows/codeql-analysis.yml
- src/js/components/Public/PublicRegisterModal.vue
- src/js/components/Shares/ShareItem.vue
> Disable buttons after click

- src/js/adminSettings.js
- src/js/dashboard.js
- src/js/store/store-polls.js
- src/js/userSettings.js
- src/js/views/Dashboard.vue
fix dashboard after store changes
> fix dashboard

- .github/workflows/lint.yml
- .github/workflows/phpunit.yml
- appinfo/info.xml
- composer.json
- composer.lock
- vendor-bin/php-cs-fixer/composer.lock
- vendor-bin/phpunit/composer.lock
- vendor-bin/psalm/composer.lock
fixes #3530
* add PHP 8.0 to supported platforms
> bring back PHP 8.0 - fixes #3530

- appinfo/info.xml
- lib/Db/CommentMapper.php
- lib/Db/OptionMapper.php
- lib/Db/PollMapper.php
- lib/Db/QBMapperWithUser.php
- lib/Db/ShareMapper.php
- lib/Db/VoteMapper.php
- package-lock.json
- package.json
> adding groupBy for PostgreSQL

- lib/Db/PollMapper.php
> switch back to $emptyString

- CHANGELOG.md
- src/js/components/Base/modules/HeaderBar.vue
- src/js/components/Poll/PollHeaderButtons.vue
- src/js/views/SideBar.vue
- src/js/views/SideBarCombo.vue
fix  #3550
Adopt new sidebar props
> Fix opening and closing of sidebar

- .github/ISSUE_TEMPLATE/ANNOUNCEMENT.yml
- CHANGELOG.md
- appinfo/info.xml
- lib/AppInfo/Application.php
- psalm-baseline.xml
> Remove service registration

- src/js/components/SideBar/SideBarTabConfiguration.vue
> Fix: sidebar archive poll

- src/js/components/Poll/PollHeaderButtons.vue
> fix poll download

- src/js/components/Comments/CommentItem.vue
- src/js/components/SideBar/SideBarTabConfiguration.vue
- src/js/components/SideBar/SideBarTabOptions.vue
> fix owner detection

- lib/Db/PollMapper.php
fixes #3572
Just guessing, that double quotation marks are a problem
> Fix joinGroupShares

- src/js/store/modules/combo.js
- src/js/views/Administration.vue
- src/js/views/PollList.vue
* Detection of archived polls was broken inside the polls list and caused a broken context menu
> fix detection of archived polls and fix context menu

- lib/AppConstants.php
- lib/Cron/AutoReminderCron.php
- lib/Cron/GroupDeletedJob.php
- lib/Cron/JanitorCron.php
- lib/Cron/NotificationCron.php
- lib/Cron/UserDeletedJob.php
- lib/Model/User/Cron.php
- lib/Model/UserBase.php
- lib/Service/MailService.php
- lib/UserSession.php
fix #3592 
should also be the reason of #3590
> allow cron user to see more user details

- src/components/SideBar/SideBarTabConfiguration.vue
> Backport #3565: Fix: sidebar archive poll

- src/js/components/Export/ExportPoll.vue
- Colon was missing from regex 
- error handling because it was failing silently
> fix: strip illegal colon from sheet name

- .github/workflows/appstore-build-publish.yml
Due to https://github.com/nextcloud-releases/polls/actions/runs/10510787323/job/29120243339
> fix: build process

- CHANGELOG.md
- src/js/assets/scss/hacks.scss
fixes #3704
Removed some old css hacks
> Fix size of creation box in navigation

- src/js/components/Public/PublicRegisterModal.vue
> fix placeholder for email input

- lib/Controller/PublicController.php
> fix vote limit for public users

- src/components/Public/PublicRegisterModal.vue
> [next] fix placeholder for email input

- lib/Cron/GroupDeletedJob.php
- lib/Cron/UserDeletedJob.php
- lib/Db/TableManager.php
- lib/Model/Mail/MailBase.php
- lib/Model/User/Contact.php
- lib/Service/MailService.php
- lib/Service/OptionService.php
- lib/Service/ShareService.php
- lib/Service/SystemService.php
Just some code maintenance for the inside Monk.
> use more contexts in logger statements

- Makefile
- sync_list.txt
- sync_list.txt.license
* Move files to sync to list file
* update make commands
> update make and sync files list

- src/components/Cards/VoteInfoCards.vue
- src/components/User/UserItem.vue
- src/components/User/UserMenu.vue
Some fixes based on console warnings
> remove warning causes

- lib/Dashboard/PollWidget.php
- lib/Db/Share.php
- lib/Provider/SearchProvider.php
> fix additional routes

- src/components/Settings/UserSettings/PerformanceSettings.vue
Change hint about performance from h3 to an info card
> put performance hint into info card

- lib/Service/SystemService.php
- tests/Unit/Db/OptionMapperTest.php
> small fixes

- lib/Db/Preferences.php
- src/components/Settings/UserSettings/StyleSettings.vue
- src/stores/preferences.ts
- src/views/Vote.vue
experimental side-by-side arrangement of description and cards on wide screens
> side by side description and cards

- lib/Controller/PublicController.php
- lib/Controller/VoteController.php
- lib/Db/Vote.php
- src/components/Export/ExportPoll.vue
- src/components/VoteTable/VoteItem.vue
- src/helpers/index.ts
- src/helpers/modules/StoreHelper.ts
- src/stores/votes.ts
- tests/Unit/Db/VoteMapperTest.php
* Return complete poll after vote and votes reset
* move voteSymbol to backend to avoid frontend iterations
> move some vote logic to backend

- appinfo/info.xml
fix #3824
raise minimum php version to 8.1 according to composer's minimum requirement
> raise minimum php version to 8.1

- src/components/Base/modules/InputDiv.vue
- src/components/Options/OptionsDateShift.vue
> fix date shifting appearence bug

- .gitignore
- lib/UserSession.php
> Fix transfer of polls via occ

- src/views/Administration.vue
Fixing admin actions take over and delete polls from other users.
related #3871
> fix takeover and delete polls in admin list

- .github/workflows/appstore-build-publish.yml
pre-releases were no more published
added `nightly:` to upload step
> add nightly parameter

- package-lock.json
- package.json
- src/components/Actions/modules/ActionRegister.vue
- src/components/Base/modules/DateTimePicker.vue
- src/components/Modals/OptionsAddModal.vue
- src/components/Options/OptionCloneDate.vue
- src/components/Options/OptionsDateAddDialog.vue
- src/components/Options/OptionsDateAddDialog_origin.vue
- src/components/Options/OptionsDateShift.vue
- src/components/Poll/PollInformation.vue
- src/constants/dateUnits.ts
- src/stores/options.ts
* Use Luxon als moment.js alternative
* add feature to directly create a new option with repetitions
* styling updates
* fixing some randomly found bugs
mobile view:
> update alternative dialog for editing options

- lib/Controller/UserController.php
- lib/Service/PreferencesService.php
> fix preferences === null

- lib/Db/Share.php
- lib/Event/BaseEvent.php
- lib/Event/CommentEvent.php
- lib/Event/OptionEvent.php
- lib/Model/UserBase.php
> cast activity rich object paramaters to string

- src/components/Activity/ActivityItem.vue
- src/components/SideBar/SideBarTabActivity.vue
- src/stores/poll.ts
> reactivate in app activities

- src/components/User/UserMenu.vue
- src/stores/options.ts
- src/stores/poll.ts
* Display view mode and options sorting as toggle inside user menu
* Change participants sort to alphabetical #3567
> Changes to user menu

- lib/Controller/CommentApiController.php
- lib/Controller/OptionApiController.php
- lib/Controller/PollApiController.php
- lib/Controller/ShareApiController.php
- lib/Controller/SubscriptionApiController.php
- lib/Controller/UserApiController.php
- lib/Controller/VoteApiController.php
> fix ocs api routes

- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
- .github/workflows/nodejs.yml
- .github/workflows/phpunit.yml
- .github/workflows/static-analysis.yml
Fix branches in workflows from `master` to `master-*`
> changed to master-*

- src/js/store/modules/pollsAdmin.js
fix https://github.com/nextcloud/polls/issues/3920
> fix: list polls after taking over

- lib/Db/Vote.php
- src/js/components/Export/ExportPoll.vue
- src/js/store/modules/votes.js
> fix: html and excel exports

- lib/Service/PollService.php
> fix access check

- src/components/VoteTable/VoteItem.vue
Remove background color from locked vote-items in list view
> fix visual issue of locked vote optoins in list view

- package-lock.json
- package.json
Until solving https://github.com/nextcloud-libraries/nextcloud-vue/issues/6720
> Temporarily lock nextcloud-vue to v9.0.0-alpha.7

- lib/Cron/JanitorCron.php
- lib/Db/Poll.php
- lib/Db/PollMapper.php
- lib/Model/Settings/AppSettings.php
- lib/Service/SettingsService.php
- src/components/Navigation/PollNavigationItems.vue
- src/components/Poll/PollInfoLine.vue
- src/components/PollList/PollItem.vue
- src/components/PollList/PollItemActions.vue
- src/components/Settings/AdminSettings/AdminDeletePolls.vue
- src/components/Settings/AdminSettings/index.ts
- src/components/SideBar/SideBarTabConfiguration.vue
- src/stores/appSettings.ts
- src/stores/combo.ts
- src/stores/poll.ts
- src/stores/polls.ts
- src/views/AdminSettingsPage.vue
* deletes archived polls after the configured time (in days) via cron job
* Added a configuration for this function
> Add auto deletion of archived polls

- CHANGELOG.md
- src/components/PollList/DeletePollDialog.vue
- src/components/PollList/PollItemActions.vue
- src/components/SideBar/SideBarTabConfiguration.vue
> Activate direct poll deletion

- CHANGELOG.md
- img/app.svg
- img/polls.svg
- lib/AppInfo/Application.php
- lib/Reference/PollReferenceProvider.php
- lib/Service/PollService.php
* implement link reference provider (simple reference)
related #3727
> implement reference provider

- src/router.ts
Invalid token resulted in an empty page
* reroute internal users to notfound 
* reroute external users to login page
> reroute user to notfound or login page

- CHANGELOG.md
- lib/Controller/CommentController.php
- lib/Db/Comment.php
- lib/Db/CommentMapper.php
- lib/Db/Poll.php
- lib/Migration/TableSchema.php
- lib/Migration/Version080000Date20250604195002.php
- lib/Service/CommentService.php
- src/Api/modules/comments.ts
- src/Api/modules/public.ts
- src/components/Comments/CommentAdd.vue
- src/components/Comments/CommentItem.vue
- src/components/Configuration/ConfigForceConfidentialComments.vue
- src/components/SideBar/SideBarTabConfiguration.vue
- src/stores/comments.ts
- src/stores/poll.ts
* update schema
* apply confidentiality
fix #2366
fix #2009
> introduce confidential comments

- appinfo/info.xml
- lib/Db/TableManager.php
* catch Exception
* change order of repair steps
fixes #4084
> Avoid broken updates on invalid vote records

- lib/Controller/PageController.php
- lib/Db/PollGroup.php
- src/router.ts
- src/stores/polls.ts
- src/stores/session.ts
- src/views/Navigation.vue
- src/views/PollList.vue
Extended the poll list to be usable for poll groups as well 
fix #4104
> poll overview for groups

- src/components/VoteTable/VoteTable.vue
List view class was not applied
fixes #4110
fixes #4111
> fix display of list-view

- lib/Provider/ActivityProvider.php
* avoid malformatted activity stream entries
> fix activity stream

- .gitignore
- src/App.vue
- src/assets/scss/vars.scss
- src/components/VoteTable/VoteTable.vue
- src/views/Vote.vue
* Limit vote table width when in list-view
* fix locked vote cell appearence
> some design and css isues, opmizations

- lib/Notification/Notifier.php
- lib/Service/ActivityService.php
- src/components/Cards/modules/CardAddProposals.vue
- src/components/User/UserSearch.vue
This fix is intended to bring the sources to respect the translation guidelines [Dos and Don'ts](https://docs.nextcloud.com/server/latest/developer_manual/basics/translations.html#dos-and-don-ts)
> fix(l10n): apply translation guidelines

- lib/Controller/PollController.php
- lib/Controller/VoteController.php
- lib/Db/OptionMapper.php
- lib/Db/Poll.php
- lib/Db/PollMapper.php
- lib/Model/Mail/ReminderMail.php
- lib/ResponseDefinitions.php
- lib/Service/OptionService.php
- src/components/Options/OptionsDateShift.vue
- src/composables/usePollWatcher.ts
- src/stores/options.ts
- src/stores/poll.ts
- src/stores/session.ts
- src/views/Vote.vue
* Squeeze some more ms out of poll loading time
* fixed wrong referenced store
> Fixes and more acceleration

- src/assets/scss/globals.scss
- src/components/VoteTable/VoteButton.vue
- src/components/VoteTable/VoteIndicator.vue
- src/components/VoteTable/VoteItem.vue
- src/components/VoteTable/VoteTable.vue
* use VoteButton for votable options of current user
* make vote cell focusable
* use leaner component for non votable vote cells
* Heavy functions got removed for better table rendering
> Make vote cell focusable

- src/components/User/UserMenu.vue
- src/stores/poll.ts
- src/stores/preferences.ts
- src/stores/session.ts
* Fix initial list view mode on mobile view
related: https://github.com/nextcloud/polls/issues/3687#issuecomment-3092359080
> fix view mode mobile

- CHANGELOG.md
- lib/Controller/PageController.php
Worker was not allowed with current CSP
> Add csp to allow worker

- src/views/SideBar.vue
* fix v-model to v-model:active
* revert async loading of sidebar tabs, NcSidebar doesn't like that
> Fix sidebar

- src/components/VoteTable/VoteTable.vue
>  keyed children of vote-table

- CHANGELOG.md
- src/views/Vote.vue
* Description could be scrolled out of view.
> move description to StickyDiv

- lib/Db/PollMapper.php
- src/components/VoteTable/VoteTable.vue
- src/stores/votes.ts
* Fix display and application of vote limitations
> fix vote limitations

- CHANGELOG.md
- lib/Db/V3/TableManager.php
- lib/Migration/Version080307Date20250826231102.php
Move table clean up to postMigration and avoid breaking migration by missing tables
fixes #4232
> move table cleaning to postMigration

- CHANGELOG.md
- lib/Filter/ActivityFilter.php
- lib/Model/UserBase.php
- lib/Provider/ActivityProvider.php
- src/stores/activity.ts
* fixed Object error with deleted users
* Added vote event to filter (Votes were not reported in siebar tab)
> Some Activity fixes

- CHANGELOG.md
- src/components/Options/OptionMenu.vue
- src/components/Options/OptionsText.vue
- src/components/SideBar/SideBarTabOptions.vue
* Fix option sorting
* fix option's menu
> Fix option sorting

- lib/Service/CalendarService.php
> Do not check deleted calendars
